'use strict';
const CFG=window.LOFOTEN_CONFIG||{};
const KEY='lofoten-pwa-v1';
const tabs=[['dashboard','Tableau de bord'],['itinerary','Itinéraire'],['family','Famille'],['map','Carte'],['van','Van'],['journal','Journal'],['budget','Budget'],['assistant','Assistant'],['sync','Synchronisation']];
const initial={
 meta:{pickup:'24/08/2026 16:00',start:'25/08/2026 06:00',return:'11/09/2026 17:00',from:'Saint-Rémy-lès-Chevreuse',to:'Champlan'},
 current:{date:'2026-08-25',place:'Saint-Rémy-lès-Chevreuse',weather:'À vérifier',olivier:5,sorya:5,paddy:5,decision:'Suivre le plan initial'},
 itinerary:[
 ['25/08','Saint-Rémy-lès-Chevreuse','Hambourg',700,7.3,'Exceptionnelle','Transit direct','Arrêt avant Brême'],['26/08','Hambourg','Jönköping',650,7,'Exceptionnelle','Danemark, ponts, Malmö','Stop Helsingborg'],['27/08','Jönköping','Gävle',520,5.8,'Normale','Contourner Stockholm','Stop plus au sud'],['28/08','Gävle','Umeå / Skellefteå',590,6.2,'Normale','E4 nord','Stop avant Umeå'],['29/08','Umeå / Skellefteå','Kiruna / Abisko',620,6.5,'Soutenue','Laponie','Stop Gällivare'],['30/08','Kiruna / Abisko','Kabelvåg / Svolvær',410,5.5,'Normale','Narvik puis E10','Nuit Narvik'],['31/08','Kabelvåg','Kabelvåg',60,1.5,'Lofoten','Henningsvær et plages','Villages/cafés'],['01/09','Kabelvåg','Leknes / Ballstad',150,3,'Lofoten','Unstad, Haukland, Uttakleiv','Limiter à deux lieux'],['02/09','Leknes / Ballstad','Reine / Sørvågen',120,3,'Lofoten','Ramberg, Nusfjord, Hamnøy','Villages si pluie'],['03/09','Reine / Sørvågen','Reine / Sørvågen',40,1,'Lofoten','Hamnøy, Reine, Å','Musées/cafés'],['04/09','Reine / Sørvågen','Reine / Sørvågen',50,1,'Lofoten','Journée météo flexible','Repos'],['05/09','Reine / Sørvågen','Fauske',550,6.5,'Soutenue','E10, Narvik, E6','Stop Narvik'],['06/09','Fauske','Mosjøen',390,5.8,'Normale','Saltfjellet','Mo i Rana'],['07/09','Mosjøen','Trondheim',390,6,'Normale','E6 sud','Stop avant Trondheim'],['08/09','Trondheim','Lillehammer / Vinstra',360,5.8,'Normale','Dovrefjell','Vinstra'],['09/09','Lillehammer','Göteborg sud',460,5.8,'Normale','Oslo puis transit','Avant Göteborg'],['10/09','Göteborg','Hanovre / Münster',750,7.5,'Exceptionnelle','Danemark puis Allemagne','Hambourg'],['11/09','Hanovre / Münster','Champlan',650,6.3,'Soutenue','Plein, nettoyage, restitution','Départ très tôt']],
 activities:[
 ['Henningsvær et port','Est','Famille A','2–3 h','Plat, aucune exposition','Oui',68.1547,14.2018],['Rørvikstranda','Est','Famille A','1 h','Plage facile','Oui',68.207,14.258],['Austnesfjorden','Est','Famille A','30–60 min','Point de vue simple','Oui',68.310,14.697],['Haukland Beach','Centre','Famille A','1–2 h','Plage et marche libre','Oui',68.199,13.529],['Haukland–Uttakleiv ancienne route','Centre','Famille B','2–3 h','Progressif, sans crête','Selon énergie',68.209,13.500],['Unstad','Centre','Famille A','1–2 h','Plage et village','Oui',68.269,13.578],['Nusfjord','Sud','Famille A','2–3 h','Village et marches courtes','Oui',68.035,13.349],['Hamnøy, Sakrisøy, Reine','Sud','Famille A','3–4 h','Points de vue accessibles','Oui',67.945,13.133],['Sørvågen et Å','Sud','Famille A','3–5 h','Villages et sentiers courts','Oui',67.881,12.983]],
 olivier:[['Reinebringen','Très raide; sortie individuelle uniquement.'],['Ryten / Kvalvika','Longue sortie, terrain humide possible.'],['Festvågtind','Raide et potentiellement exposé.'],['Mannen','Crête, sensation de vide possible.']],
 van:{fuel:100,water:100,grey:0,battery:100,toilet:'OK',next:'Contrôle complet avant départ'},
 journal:[],expenses:[],gps:{km:0,points:[]},updatedAt:null
};
const clone=x=>JSON.parse(JSON.stringify(x));
let state=load();let active='dashboard';let watchId=null;let tokenClient=null;let accessToken='';let leafletMap=null;
function load(){try{return Object.assign(clone(initial),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(initial)}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));setSync('local')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function byId(id){return document.getElementById(id)}
function totalKm(){return state.itinerary.reduce((a,r)=>a+(Number(r[3])||0),0)}
function setSync(mode,msg){const dot=byId('sync-dot'),label=byId('sync-label');if(!dot||!label)return;dot.className='dot '+(mode==='online'?'online':'offline');label.textContent=msg||(mode==='online'?'Synchronisé Google':'Mode local')}
function init(){renderNav();show('dashboard');byId('google-login').addEventListener('click',googleLogin);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);window.addEventListener('online',()=>setSync(accessToken?'online':'local'))}
function renderNav(){const nav=byId('nav');tabs.forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.dataset.tab=id;b.onclick=()=>show(id);nav.appendChild(b)})}
function show(id){active=id;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));({dashboard:renderDashboard,itinerary:renderItinerary,family:renderFamily,map:renderMap,van:renderVan,journal:renderJournal,budget:renderBudget,assistant:renderAssistant,sync:renderSync}[id])()}
function card(label,value,sub=''){return `<div class="card kpi"><span class="muted">${esc(label)}</span><br><strong>${esc(value)}</strong>${sub?`<br><span>${esc(sub)}</span>`:''}</div>`}
function renderDashboard(){byId('app').innerHTML=`<div class="grid">${card('Prise du van',state.meta.pickup)}${card('Départ',state.meta.start,state.meta.from)}${card('Restitution',state.meta.return,state.meta.to)}${card('Distance prévue',totalKm().toLocaleString('fr-FR')+' km')}${card('GPS enregistré',(state.gps.km||0).toFixed(1)+' km')}</div><div class="grid" style="margin-top:12px"><section class="card"><h2>État actuel</h2><div class="form"><label>Date<input id="c-date" type="date" value="${esc(state.current.date)}"></label><label>Position<input id="c-place" value="${esc(state.current.place)}"></label><label>Météo<input id="c-weather" value="${esc(state.current.weather)}"></label><label>Énergie Olivier /5<input id="c-o" type="number" min="1" max="5" value="${state.current.olivier}"></label><label>Énergie Sorya /5<input id="c-s" type="number" min="1" max="5" value="${state.current.sorya}"></label><label>Énergie Paddy /5<input id="c-p" type="number" min="1" max="5" value="${state.current.paddy}"></label></div><label>Décision<textarea id="c-decision">${esc(state.current.decision)}</textarea></label><button id="save-current" class="primary">Enregistrer</button></section><section class="card"><h2>Suivi GPS</h2><p class="muted">Une page web ne garantit pas le suivi lorsque le téléphone est verrouillé.</p><div class="toolbar"><button id="gps-start" class="primary">Démarrer</button><button id="gps-stop">Arrêter</button><button id="gps-reset" class="danger">Réinitialiser</button></div><div id="gps-status" class="status">Suivi inactif</div></section></div><section class="card" style="margin-top:12px"><b>Principe familial :</b> aucune activité commune très raide, aérienne ou exposée. Les options sportives d’Olivier restent séparées.</section>`;byId('save-current').onclick=()=>{state.current={date:byId('c-date').value,place:byId('c-place').value,weather:byId('c-weather').value,olivier:+byId('c-o').value,sorya:+byId('c-s').value,paddy:+byId('c-p').value,decision:byId('c-decision').value};save();autoSync()};byId('gps-start').onclick=startGPS;byId('gps-stop').onclick=stopGPS;byId('gps-reset').onclick=()=>{if(confirm('Effacer la trace GPS ?')){state.gps={km:0,points:[]};save();renderDashboard()}}}
function editableTable(data,headers,name){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}<th></th></tr></thead><tbody>${data.map((r,i)=>`<tr>${r.map((v,j)=>`<td contenteditable="true" data-table="${name}" data-row="${i}" data-col="${j}">${esc(v)}</td>`).join('')}<td><button class="danger delete-row" data-table="${name}" data-row="${i}">×</button></td></tr>`).join('')}</tbody></table></div>`}
function bindEditable(name,rerender){document.querySelectorAll(`[data-table="${name}"][contenteditable]`).forEach(td=>td.onblur=()=>{let v=td.innerText.trim();if((name==='itinerary'&&(td.dataset.col==='3'||td.dataset.col==='4'))||(name==='expenses'&&td.dataset.col==='1'))v=Number(v.replace(',','.'))||0;state[name][+td.dataset.row][+td.dataset.col]=v;save();autoSync()});document.querySelectorAll(`.delete-row[data-table="${name}"]`).forEach(b=>b.onclick=()=>{state[name].splice(+b.dataset.row,1);save();rerender();autoSync()})}
function renderItinerary(){byId('app').innerHTML=`<section class="card"><h2>Itinéraire modifiable</h2><div class="toolbar"><button id="add-leg" class="primary">Ajouter une étape</button><button id="reset-leg">Restaurer</button></div>${editableTable(state.itinerary,['Date','Départ','Arrivée','Km','Heures','Type','Plan A','Plan B'],'itinerary')}</section>`;bindEditable('itinerary',renderItinerary);byId('add-leg').onclick=()=>{state.itinerary.push(['Date','Départ','Arrivée',0,0,'Normale','Plan A','Plan B']);save();renderItinerary()};byId('reset-leg').onclick=()=>{if(confirm('Restaurer l’itinéraire initial ?')){state.itinerary=clone(initial.itinerary);save();renderItinerary()}}}
function renderFamily(){byId('app').innerHTML=`<section class="card"><h2>Activités famille — Sorya & Paddy en priorité</h2>${editableTable(state.activities,['Activité','Secteur','Catégorie','Durée','Terrain','Paddy','Latitude','Longitude'],'activities')}</section><h2>Options Olivier</h2><div class="grid">${state.olivier.map(x=>`<div class="card"><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></div>`).join('')}</div>`;bindEditable('activities',renderFamily)}
function renderMap(){byId('app').innerHTML=`<section class="card"><h2>Carte du voyage</h2><div class="toolbar"><button id="map-family" class="primary">Activités famille</button><button id="map-gps">Trace GPS</button><a class="btn" target="_blank" rel="noopener" href="https://www.vegvesen.no/trafikk/">Trafic Norvège</a></div><div id="map-canvas" class="map"></div></section>`;setTimeout(()=>{leafletMap=L.map('map-canvas').setView([67.95,13.1],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(leafletMap);plotFamily();byId('map-family').onclick=plotFamily;byId('map-gps').onclick=plotGPS},0)}
function plotFamily(){if(!leafletMap)return;state.activities.forEach(a=>{const lat=Number(a[6]),lon=Number(a[7]);if(Number.isFinite(lat)&&Number.isFinite(lon))L.marker([lat,lon]).addTo(leafletMap).bindPopup(`<b>${esc(a[0])}</b><br>${esc(a[2])}<br>${esc(a[4])}`)})}
function plotGPS(){if(!leafletMap||state.gps.points.length<2)return;const pts=state.gps.points.map(p=>[p.lat,p.lon]);L.polyline(pts,{weight:4}).addTo(leafletMap);leafletMap.fitBounds(pts)}
function renderVan(){const meter=(label,key)=>`<div class="card"><div class="range-row"><b>${label}</b><input data-vankey="${key}" type="range" min="0" max="100" value="${state.van[key]}"><output>${state.van[key]}%</output></div></div>`;byId('app').innerHTML=`<div class="grid">${meter('Carburant','fuel')}${meter('Eau propre','water')}${meter('Eaux grises','grey')}${meter('Batterie','battery')}</div><section class="card" style="margin-top:12px"><div class="form"><label>Toilettes<select id="toilet"><option>OK</option><option>À vider</option><option>À traiter</option></select></label><label>Action suivante<input id="van-next" value="${esc(state.van.next)}"></label></div><button id="save-van" class="primary">Enregistrer</button></section>`;byId('toilet').value=state.van.toilet;document.querySelectorAll('[data-vankey]').forEach(r=>r.oninput=()=>r.nextElementSibling.value=r.value+'%');byId('save-van').onclick=()=>{document.querySelectorAll('[data-vankey]').forEach(r=>state.van[r.dataset.vankey]=+r.value);state.van.toilet=byId('toilet').value;state.van.next=byId('van-next').value;save();autoSync();renderVan()}}
function renderJournal(){const rows=state.journal.map((x,i)=>`<tr><td>${esc(x.date)}</td><td>${esc(x.place)}</td><td>${esc(x.km)}</td><td>${esc(x.weather)}</td><td>${esc(x.highlight)}</td><td>${esc(x.issue)}</td><td><button class="danger" data-j="${i}">×</button></td></tr>`).join('');byId('app').innerHTML=`<section class="card"><h2>Nouvelle entrée</h2><div class="form"><input id="j-date" type="date" value="${state.current.date}"><input id="j-place" placeholder="Lieu"><input id="j-km" type="number" placeholder="Km"><input id="j-weather" placeholder="Météo"></div><textarea id="j-highlight" placeholder="Moment fort"></textarea><textarea id="j-issue" placeholder="Aléa / décision"></textarea><button id="j-add" class="primary">Ajouter</button></section><section class="card" style="margin-top:12px"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Lieu</th><th>Km</th><th>Météo</th><th>Moment fort</th><th>Aléa</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`;byId('j-add').onclick=()=>{state.journal.unshift({date:byId('j-date').value,place:byId('j-place').value,km:+byId('j-km').value||0,weather:byId('j-weather').value,highlight:byId('j-highlight').value,issue:byId('j-issue').value});save();autoSync();renderJournal()};document.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>{state.journal.splice(+b.dataset.j,1);save();renderJournal();autoSync()})}
function renderBudget(){const total=state.expenses.reduce((a,r)=>a+(Number(r[1])||0),0);byId('app').innerHTML=`<div class="grid"><div class="card"><span class="muted">Dépenses enregistrées</span><div class="expense-total">${total.toFixed(2)} €</div></div><div class="card"><h3>Ajouter</h3><div class="form"><input id="e-cat" placeholder="Catégorie"><input id="e-amount" type="number" step="0.01" placeholder="Montant €"><input id="e-place" placeholder="Lieu"><input id="e-note" placeholder="Note"></div><button id="e-add" class="primary">Ajouter</button></div></div><section class="card" style="margin-top:12px">${editableTable(state.expenses,['Catégorie','Montant €','Lieu','Note','Date'],'expenses')}</section>`;bindEditable('expenses',renderBudget);byId('e-add').onclick=()=>{state.expenses.push([byId('e-cat').value,+byId('e-amount').value||0,byId('e-place').value,byId('e-note').value,new Date().toISOString().slice(0,10)]);save();autoSync();renderBudget()}}
function renderAssistant(){byId('app').innerHTML=`<div class="grid"><section class="card"><h2>Assistant de replanification</h2><p class="muted">Version locale basée sur vos règles de sécurité et de fatigue.</p><textarea id="a-input" placeholder="Exemple : Nous sommes fatigués et il pleut demain à Reine."></textarea><button id="a-run" class="primary">Proposer un ajustement</button></section><section class="card"><h2>Recommandation</h2><div id="a-output" class="status">Décris la situation.</div></section></div>`;byId('a-run').onclick=()=>{const q=byId('a-input').value.toLowerCase();let out=[];if(/fatigu|épuis|tired/.test(q))out.push('Réduire la conduite et choisir immédiatement le Plan B de l’étape.');if(/pluie|rain/.test(q))out.push('Reporter toute randonnée raide; privilégier Nusfjord, les villages, les plages et les cafés.');if(/vent|rafale/.test(q))out.push('Éviter crêtes, Reinebringen, Festvågtind, Ryten et les plages très exposées.');if(/paddy|chien/.test(q))out.push('Prévoir une sortie courte, terrain simple, pauses fréquentes et possibilité de le porter.');if(/retard/.test(q))out.push('Supprimer une activité optionnelle plutôt que prolonger une journée au-delà de 7 h 30.');if(!out.length)out=['Conserver le programme familial, vérifier Yr et Vegvesen, puis choisir l’activité la moins exposée.'];byId('a-output').innerHTML='<ul>'+out.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>'}}
function renderSync(){const configured=Boolean(CFG.googleClientId&&CFG.spreadsheetId);byId('app').innerHTML=`<div class="grid"><section class="card"><h2>Google Sheets</h2><p>${configured?'Configuration détectée. Connecte-toi pour synchroniser.':'L’identifiant OAuth Google manque encore dans config.js.'}</p><div class="toolbar"><button id="sync-login" class="primary">Connexion Google</button><button id="sync-push">Envoyer vers Sheets</button><button id="sync-pull">Charger depuis Sheets</button></div><p class="muted">Spreadsheet : ${esc(CFG.spreadsheetId||'non défini')}</p></section><section class="card"><h2>Sauvegarde de secours</h2><div class="toolbar"><button id="export-json">Exporter JSON</button><button id="import-json">Importer JSON</button><button id="reset-all" class="danger">Tout réinitialiser</button></div></section></div>`;byId('sync-login').onclick=googleLogin;byId('sync-push').onclick=pushAll;byId('sync-pull').onclick=pullAll;byId('export-json').onclick=exportJSON;byId('import-json').onclick=()=>byId('json-file').click();byId('reset-all').onclick=()=>{if(confirm('Tout effacer localement ?')){state=clone(initial);save();show('dashboard')}}}
function startGPS(){if(!navigator.geolocation)return alert('GPS indisponible.');if(watchId!==null)return;const box=byId('gps-status');if(box)box.textContent='Recherche de position…';watchId=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude,t:new Date().toISOString(),acc:pos.coords.accuracy};const last=state.gps.points.at(-1);if(last&&p.acc<100){const d=distance(last,p);if(d<5)state.gps.km+=d}state.gps.points.push(p);save();if(box)box.textContent=`GPS actif · précision ${Math.round(p.acc)} m · ${state.gps.km.toFixed(1)} km`;autoSync()},err=>{if(box)box.textContent='Erreur GPS : '+err.message},{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
function stopGPS(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;const b=byId('gps-status');if(b)b.textContent='Suivi arrêté'}
function distance(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,q=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function googleLogin(){if(!CFG.googleClientId)return alert('Ajoute d’abord le Client ID OAuth Google dans config.js.');if(!window.google?.accounts?.oauth2)return alert('Le service Google Identity n’est pas encore chargé. Réessaie dans quelques secondes.');tokenClient=google.accounts.oauth2.initTokenClient({client_id:CFG.googleClientId,scope:'https://www.googleapis.com/auth/spreadsheets',callback:r=>{if(r.error)return alert(r.error);accessToken=r.access_token;setSync('online','Connecté à Google');pullAll()}});tokenClient.requestAccessToken({prompt:accessToken?'':'consent'})}
async function api(path,opts={}){if(!accessToken)throw new Error('Connexion Google requise');const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+CFG.spreadsheetId+path,{...opts,headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
const ranges=()=>({Settings:[['key','value'],['state_json',JSON.stringify(state)]],Itinerary:[['Date','Départ','Arrivée','Km','Heures','Type','Plan A','Plan B'],...state.itinerary],Activities:[['Activité','Secteur','Catégorie','Durée','Terrain','Paddy','Lat','Lon'],...state.activities],Current_Status:[['date','place','weather','olivier','sorya','paddy','decision'],[state.current.date,state.current.place,state.current.weather,state.current.olivier,state.current.sorya,state.current.paddy,state.current.decision]],Van_Log:[['fuel','water','grey','battery','toilet','next'],[state.van.fuel,state.van.water,state.van.grey,state.van.battery,state.van.toilet,state.van.next]],Journal:[['date','place','km','weather','highlight','issue'],...state.journal.map(x=>[x.date,x.place,x.km,x.weather,x.highlight,x.issue])],GPS_Track:[['lat','lon','time','accuracy'],...state.gps.points.map(p=>[p.lat,p.lon,p.t,p.acc])],Expenses:[['category','amount','place','note','date'],...state.expenses]});
async function ensureSheets(){const meta=await api('?fields=sheets.properties');const existing=new Set((meta.sheets||[]).map(s=>s.properties.title));const requests=Object.keys(ranges()).filter(n=>!existing.has(n)).map(title=>({addSheet:{properties:{title}}}));if(requests.length)await api(':batchUpdate',{method:'POST',body:JSON.stringify({requests})})}
async function pushAll(){try{setSync('local','Synchronisation…');await ensureSheets();const data=ranges();for(const [name,values] of Object.entries(data)){await api(`/values/${encodeURIComponent(name+'!A1:Z500')}?valueInputOption=RAW`,{method:'PUT',body:JSON.stringify({range:name+'!A1:Z500',majorDimension:'ROWS',values})})}setSync('online','Synchronisé')}catch(e){console.error(e);setSync('local','Erreur de synchronisation');alert(e.message)}}
async function pullAll(){try{setSync('local','Chargement Google…');const r=await api(`/values/${encodeURIComponent('Settings!A1:B10')}`);const json=(r.values||[]).find(x=>x[0]==='state_json')?.[1];if(json){state=Object.assign(clone(initial),JSON.parse(json));save();setSync('online','Chargé depuis Google');show(active)}else setSync('online','Google prêt')}catch(e){console.warn(e);setSync('online','Google prêt — aucune donnée')}}
let syncTimer=null;function autoSync(){if(!accessToken)return;clearTimeout(syncTimer);syncTimer=setTimeout(pushAll,1200)}
function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lofoten-2026-roadbook.json';a.click();URL.revokeObjectURL(a.href)}
byId('json-file').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=Object.assign(clone(initial),JSON.parse(r.result));save();show('dashboard')}catch{alert('JSON invalide')}};r.readAsText(f)});
window.addEventListener('DOMContentLoaded',init);
