'use strict';

const FAMILY_HIKES=[
 {key:'linken',name:'Linken Svolvær',island:'Austvågøy',distance:'3,8 km A/R',duration:'~1 h',altitude:'152 m',effort:'1/5',grade:'Facile',paddy:'Oui, si terrain sec et tenu en laisse',caution:'Courte montée vers un point de vue accessible; bonnes chaussures même sur ce parcours facile.',url:'https://lofotenhikes.com/hike/linken-svolvaer-105m/',lat:68.235,lon:14.565},
 {key:'hoven',name:'Hoven',island:'Gimsøy',distance:'3,8 km A/R',duration:'~2–2 h 30',altitude:'367 m',effort:'2/5',grade:'Facile à modérée',paddy:'Oui, selon vent et terrain',caution:'Pente herbeuse régulière sans passage technique; éviter par vent fort ou sol très humide.',url:'https://lofotenhikes.com/hike/hoven-367m/',lat:68.322,lon:14.116},
 {key:'kvalvika',name:'Kvalvika Beach',island:'Moskenesøy',distance:'4 km A/R',duration:'~3 h',altitude:'180 m de dénivelé',effort:'2,5/5',grade:'Facile mais terrain irrégulier',paddy:'Oui, avec vigilance',caution:'Sentier rocheux et parfois boueux; descente vers la plage et retour plus fatigants qu’une simple promenade.',url:'https://lofotenhikes.com/hike/kvalvika-beach/',lat:68.091,lon:13.124},
 {key:'bunes',name:'Bunes Beach',island:'Moskenesøy',distance:'5,6 km A/R',duration:'~2–4 h',altitude:'80 m',effort:'1,5/5',grade:'Facile',paddy:'Oui, sous réserve des règles du bateau',caution:'Accès uniquement par bateau depuis Reine vers Vindstad; vérifier horaires, météo et retour avant de partir.',url:'https://visitlofoten.com/en/guide/bunes-beach-hiking-trail-in-lofoten/',lat:67.997,lon:12.948},
 {key:'holandsmaelen',name:'Holandsmælen',island:'Vestvågøy',distance:'5–6 km A/R',duration:'~2–3 h',altitude:'434 m',effort:'2,5/5',grade:'Modérée accessible',paddy:'Selon énergie et météo',caution:'Montée progressive avec quelques sections plus raides; privilégier une journée sèche et peu venteuse.',url:'https://lofotenhikes.com/hike/holandsmaelen-434m/',lat:68.184,lon:13.562},
 {key:'haen-family',name:'Håen / Håheia',island:'Værøy',distance:'5,7 km A/R',duration:'~3 h',altitude:'438 m',effort:'2/5',grade:'Facile à modérée',paddy:'Oui, mais jamais près des falaises',caution:'Ancienne route militaire agréable; ferry nécessaire et falaises sommitales extrêmement abruptes.',url:'https://lofotenhikes.com/hike/haen-haheia-438m/',lat:67.663,lon:12.667}
];

function familyHikePlanned(h){return state.activities.some(a=>String(a[0]).toLowerCase().includes(h.name.toLowerCase().split(' / ')[0]));}
function familyHikeCard(h){const planned=familyHikePlanned(h);return `<article class="hike-card family-card ${planned?'planned':''}"><div class="hike-card-head"><div><span class="hike-island">${esc(h.island)}</span><h3>${esc(h.name)}</h3></div><span class="hike-status ${planned?'':'alt'}">${planned?'Planifiée':'Option famille'}</span></div><div class="hike-metrics"><span><b>${esc(h.distance)}</b><small>Distance</small></span><span><b>${esc(h.duration)}</b><small>Durée</small></span><span><b>${esc(h.altitude)}</b><small>Altitude</small></span><span><b>${esc(h.effort)}</b><small>Effort</small></span></div><p><b>${esc(h.grade)}</b> · Paddy : ${esc(h.paddy)}</p><p class="muted">${esc(h.caution)}</p><div class="toolbar"><a class="btn primary" href="${h.url}" target="_blank" rel="noopener">Voir la fiche ↗</a>${planned?`<button class="remove-family-hike" data-key="${h.key}">Retirer</button>`:`<button class="add-family-hike" data-key="${h.key}">Ajouter au programme famille</button>`}</div></article>`;}

function renderFamilyPriority(){
 const plannedSport=LOFOTEN_HIKES.filter(h=>state.olivier.some(x=>hikeSourceForName(x[0])?.key===h.key));
 byId('app').innerHTML=`<section class="card priority-banner"><h2>Priorité du voyage : randonnées en famille</h2><p>Le programme principal doit convenir à Sorya et Paddy. Les randonnées sportives d’Olivier restent optionnelles et ne doivent jamais imposer le rythme familial.</p></section><section class="card hike-library"><div class="map-heading"><div><h2>Randonnées famille recommandées</h2><p class="muted">Sélection courte, accessible et répartie sur plusieurs îles. Vérifier météo, vent, boue, parking et règles pour Paddy avant chaque départ.</p></div><div class="toolbar"><a class="btn" href="https://lofotenhikes.com/difficulty/easy/" target="_blank" rel="noopener">Randonnées faciles ↗</a><a class="btn" href="https://lofotenhikes.com/map/" target="_blank" rel="noopener">Carte LofotenHikes ↗</a></div></div><div class="hike-grid">${FAMILY_HIKES.map(familyHikeCard).join('')}</div></section><section class="card"><h2>Autres activités famille déjà prévues</h2>${editableTable(state.activities,['Activité','Secteur','Catégorie','Durée','Terrain','Paddy','Latitude','Longitude'],'activities')}</section><section class="card hike-library bonus-section"><h2>Bonus Olivier — uniquement si les conditions et le planning familial le permettent</h2><p class="muted">Ces sorties ne sont pas prioritaires et peuvent être supprimées sans remettre en cause le voyage.</p><div class="hike-grid">${plannedSport.length?plannedSport.map(h=>hikeCard(h,true)).join(''):'<p class="status">Aucune randonnée sportive planifiée.</p>'}</div></section>`;
 bindEditable('activities',renderFamilyPriority);
 document.querySelectorAll('.add-family-hike').forEach(b=>b.onclick=()=>{const h=FAMILY_HIKES.find(x=>x.key===b.dataset.key);if(!h||familyHikePlanned(h))return;state.activities.push([h.name,h.island,'Famille randonnée',h.duration,h.grade,h.paddy,h.lat,h.lon]);save();autoSync();renderFamilyPriority();});
 document.querySelectorAll('.remove-family-hike').forEach(b=>b.onclick=()=>{const h=FAMILY_HIKES.find(x=>x.key===b.dataset.key);if(!h)return;state.activities=state.activities.filter(a=>!String(a[0]).toLowerCase().includes(h.name.toLowerCase().split(' / ')[0]));save();autoSync();renderFamilyPriority();});
 document.querySelectorAll('.remove-hike').forEach(button=>button.onclick=()=>{const key=button.dataset.hike;state.olivier=state.olivier.filter(x=>hikeSourceForName(x[0])?.key!==key);save();autoSync();renderFamilyPriority();});
}

renderFamily=renderFamilyPriority;
