'use strict';

const LOFOTEN_HIKES = [
  {key:'reinebringen',name:'Reinebringen',title:'Reinebringen (448m)',island:'Moskenesøy',altitude:'448 m',distance:'2 km aller-retour',duration:'~2 h',effort:'3,5/5',grade:'Modérée, très raide',caution:'Environ 1 970 marches; descente exigeante pour les genoux; fréquentation et stationnement à anticiper.',lat:67.922333,lon:13.078361,url:'https://lofotenhikes.com/hike/reinebringen-448m/',traceUrl:'https://lofotenhikes.com/hike/reinebringen-448m/#route-map',fallbackUrl:'https://hikes-and-walks.com/hike/norway/reinebringen',fallbackLabel:'Guide alternatif'},
  {key:'ryten',name:'Ryten / Kvalvika',title:'Ryten (543m)',island:'Moskenesøy',altitude:'543 m',distance:'7,3 km aller-retour',duration:'~5 h',effort:'3/5',grade:'Modérée',caution:'Terrain humide et boueux possible; sommet exposé au vent; bien distinguer la bifurcation vers Kvalvika.',lat:68.090539,lon:13.156741,url:'https://lofotenhikes.com/hike/ryten-543m/',traceUrl:'https://lofotenhikes.com/hike/ryten-543m/#route-map',fallbackUrl:'https://www.journeysjar.com/en/mountain-ranges/lofoten/ryten',fallbackLabel:'Guide alternatif'},
  {key:'festvagtinden',name:'Festvågtind',title:'Festvågtinden (541m)',island:'Austvågøy',altitude:'541 m',distance:'2,3 km aller-retour',duration:'~2–3 h',effort:'3,5/5',grade:'Courte mais raide',caution:'Premier tronçon rocheux et très raide; rochers glissants lorsqu’ils sont mouillés; partir tôt pour le parking.',lat:68.171693,lon:14.220374,url:'https://lofotenhikes.com/hike/festvagtinden-541m/',traceUrl:'https://lofotenhikes.com/hike/festvagtinden-541m/#route-map',fallbackUrl:'https://www.outdooractive.com/en/route/hiking-trail/lofoten/festvagtind/56037325/',fallbackLabel:'Carte Outdooractive'},
  {key:'mannen',name:'Mannen',title:'Mannen (400m)',island:'Vestvågøy',altitude:'400 m',distance:'4,1 km aller-retour',duration:'~3 h',effort:'3/5',grade:'Modérée',caution:'Crête finale plus étroite et exposée; éviter par vent fort, pluie ou terrain glissant.',lat:68.199630,lon:13.532630,url:'https://lofotenhikes.com/hike/mannen-400m/',traceUrl:'https://lofotenhikes.com/hike/mannen-400m/#route-map',fallbackUrl:'https://visitlofoten.com/en/guide/mannen-400-m/',fallbackLabel:'Visit Lofoten'},
  {key:'haen',name:'Håen / Håheia',title:'Håen (Håheia) 438m',island:'Værøy',altitude:'438 m',distance:'5,7 km aller-retour',duration:'~3 h',effort:'2/5',grade:'Modérée, montée douce',caution:'Værøy impose une traversée en ferry; rester très loin des falaises sommitales, particulièrement avec enfants ou chien.',lat:67.672383,lon:12.658083,url:'https://lofotenhikes.com/hike/haen-haheia-438m/',traceUrl:'https://lofotenhikes.com/hike/haen-haheia-438m/#route-map',fallbackUrl:'https://visitlofoten.com/en/activity/hiking/hike-to-haheia-at-vaeroy-438-m/',fallbackLabel:'Visit Lofoten'}
];

function hikeSourceForName(name){const n=String(name||'').toLowerCase();return LOFOTEN_HIKES.find(h=>n.includes(h.key)||n.includes(h.name.toLowerCase().split(' / ')[0])||h.name.toLowerCase().includes(n))}
function hikeLinks(h){return `<a href="${h.url}" target="_blank" rel="noopener">Description ↗</a> · <a href="${h.traceUrl||h.url}" target="_blank" rel="noopener"><b>Voir le tracé 2D/3D ↗</b></a>${h.fallbackUrl?` · <a href="${h.fallbackUrl}" target="_blank" rel="noopener">${esc(h.fallbackLabel||'Alternative')} ↗</a>`:''}`}
function hikeCard(h,planned=false){return `<article class="hike-card ${planned?'planned':''}"><div class="hike-card-head"><div><span class="hike-island">${esc(h.island)}</span><h3>${esc(h.title)}</h3></div>${planned?'<span class="hike-status">Planifiée</span>':'<span class="hike-status alt">Alternative</span>'}</div><div class="hike-metrics"><span><b>${esc(h.distance)}</b><small>Distance</small></span><span><b>${esc(h.duration)}</b><small>Durée</small></span><span><b>${esc(h.altitude)}</b><small>Sommet</small></span><span><b>${esc(h.effort)}</b><small>Effort</small></span></div><p><b>${esc(h.grade)}</b></p><p class="muted">${esc(h.caution)}</p><div class="toolbar"><a class="btn" href="${h.url}" target="_blank" rel="noopener">Description ↗</a><a class="btn primary" href="${h.traceUrl||h.url}" target="_blank" rel="noopener">🗺️ Voir le tracé 2D/3D ↗</a>${h.fallbackUrl?`<a class="btn" href="${h.fallbackUrl}" target="_blank" rel="noopener">${esc(h.fallbackLabel||'Alternative')} ↗</a>`:''}${planned?`<button class="remove-hike" data-hike="${h.key}">Retirer du plan</button>`:`<button class="add-hike" data-hike="${h.key}">Ajouter au plan</button>`}</div></article>`}

function renderFamilyEnhanced(){
  const planned=LOFOTEN_HIKES.filter(h=>state.olivier.some(x=>hikeSourceForName(x[0])?.key===h.key));const alternatives=LOFOTEN_HIKES.filter(h=>!planned.some(p=>p.key===h.key));
  byId('app').innerHTML=`<section class="card"><h2>Activités famille — Sorya & Paddy en priorité</h2>${editableTable(state.activities,['Activité','Secteur','Catégorie','Durée','Terrain','Paddy','Latitude','Longitude'],'activities')}</section><section class="card hike-library"><div class="map-heading"><div><h2>Randonnées prévues — Olivier</h2><p class="muted">Chaque fiche permet d’ouvrir séparément la description et le tracé interactif 2D/3D dans un nouvel onglet.</p></div><div class="toolbar"><a class="btn" href="https://lofotenhikes.com/all-hikes/" target="_blank" rel="noopener">Toutes les randonnées ↗</a><a class="btn" href="https://lofotenhikes.com/map/" target="_blank" rel="noopener">Carte LofotenHikes ↗</a></div></div><div class="hike-grid">${planned.length?planned.map(h=>hikeCard(h,true)).join(''):'<p class="status">Aucune randonnée sportive planifiée.</p>'}</div></section><section class="card hike-library"><h2>Changer de randonnée pendant le voyage</h2><div class="hike-grid">${alternatives.map(h=>hikeCard(h,false)).join('')}</div></section>`;
  bindEditable('activities',renderFamilyEnhanced);
  document.querySelectorAll('.add-hike').forEach(button=>button.onclick=()=>{const h=LOFOTEN_HIKES.find(x=>x.key===button.dataset.hike);if(h&&!state.olivier.some(x=>hikeSourceForName(x[0])?.key===h.key))state.olivier.push([h.name,h.caution]);save();autoSync();renderFamilyEnhanced()});
  document.querySelectorAll('.remove-hike').forEach(button=>button.onclick=()=>{state.olivier=state.olivier.filter(x=>hikeSourceForName(x[0])?.key!==button.dataset.hike);save();autoSync();renderFamilyEnhanced()});
}

function showHikingMapEnhanced(){
  byId('hike-view').classList.add('primary');byId('road-view').classList.remove('primary');baseMap([68.08,13.45],9,true);const bounds=[];
  state.activities.forEach((a,i)=>{const lat=Number(a[6]),lon=Number(a[7]);if(Number.isFinite(lat)&&Number.isFinite(lon)){bounds.push([lat,lon]);const source=hikeSourceForName(a[0]);const link=source?`<br>${hikeLinks(source)}`:'';L.marker([lat,lon],{icon:numberedIcon(i+1,'hike')}).addTo(leafletMap).bindPopup(`<b>${esc(a[0])}</b><br>${esc(a[2])} · ${esc(a[3])}<br>${esc(a[4])}<br>Paddy : ${esc(a[5])}${link}`)}});
  const plannedKeys=new Set(state.olivier.map(x=>hikeSourceForName(x[0])?.key).filter(Boolean));
  LOFOTEN_HIKES.forEach(h=>{bounds.push([h.lat,h.lon]);const planned=plannedKeys.has(h.key);L.marker([h.lat,h.lon],{icon:L.divIcon({className:'numbered-marker hike',html:`<span>${planned?'🥾':'○'}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}).addTo(leafletMap).bindPopup(`<b>${esc(h.title)}</b><br>${esc(h.island)} · ${esc(h.distance)} · ${esc(h.duration)}<br>${esc(h.grade)}<br><span class="muted">${esc(h.caution)}</span><br>${hikeLinks(h)}`)});
  if(state.gps.points.length>1){const pts=state.gps.points.map(p=>[p.lat,p.lon]);L.polyline(pts,{weight:4}).addTo(leafletMap);bounds.push(...pts)}
  if(bounds.length)leafletMap.fitBounds(bounds,{padding:[25,25],maxZoom:11});
  byId('map-summary').innerHTML=`<div><strong>${state.activities.length}</strong><span>activités familiales</span></div><div><strong>${LOFOTEN_HIKES.length}</strong><span>randonnées documentées</span></div><div><strong>${state.gps.points.length}</strong><span>points GPS enregistrés</span></div>`;
  byId('route-status').textContent='Clique sur une randonnée, puis sur « Voir le tracé 2D/3D » pour ouvrir le parcours dans un nouvel onglet.';
  byId('map-legend').innerHTML='<span><i class="dot-hike"></i>Activités famille</span><span>🥾 randonnée planifiée · ○ alternative</span><a target="_blank" rel="noopener" href="https://lofotenhikes.com/map/">Carte LofotenHikes ↗</a>';
}

renderFamily=renderFamilyEnhanced;
showHikingMap=showHikingMapEnhanced;