'use strict';

const LOFOTEN_HIKES = [
  {key:'reinebringen',name:'Reinebringen',title:'Reinebringen (448m)',island:'Moskenesøy',altitude:'448 m',distance:'2 km aller-retour',duration:'~2 h',effort:'3,5/5',grade:'Modérée, très raide',crowd:'Très fréquentée',caution:'Environ 1 970 marches; descente exigeante pour les genoux; fréquentation et stationnement à anticiper.',lat:67.922333,lon:13.078361,url:'https://lofotenhikes.com/hike/reinebringen-448m/',traceUrl:'https://lofotenhikes.com/hike/reinebringen-448m/#route-map',fallbackUrl:'https://hikes-and-walks.com/hike/norway/reinebringen',fallbackLabel:'Guide alternatif'},
  {key:'ryten',name:'Ryten / Kvalvika',title:'Ryten (543m)',island:'Moskenesøy',altitude:'543 m',distance:'7,3 km aller-retour',duration:'~5 h',effort:'3/5',grade:'Modérée',crowd:'Très fréquentée',caution:'Terrain humide et boueux possible; sommet exposé au vent; bien distinguer la bifurcation vers Kvalvika.',lat:68.090539,lon:13.156741,url:'https://lofotenhikes.com/hike/ryten-543m/',traceUrl:'https://lofotenhikes.com/hike/ryten-543m/#route-map',fallbackUrl:'https://www.journeysjar.com/en/mountain-ranges/lofoten/ryten',fallbackLabel:'Guide alternatif'},
  {key:'festvagtinden',name:'Festvågtind',title:'Festvågtinden (541m)',island:'Austvågøy',altitude:'541 m',distance:'2,3 km aller-retour',duration:'~2–3 h',effort:'3,5/5',grade:'Courte mais raide',crowd:'Très fréquentée',caution:'Premier tronçon rocheux et très raide; rochers glissants lorsqu’ils sont mouillés; partir tôt pour le parking.',lat:68.171693,lon:14.220374,url:'https://lofotenhikes.com/hike/festvagtinden-541m/',traceUrl:'https://lofotenhikes.com/hike/festvagtinden-541m/#route-map',fallbackUrl:'https://www.outdooractive.com/en/route/hiking-trail/lofoten/festvagtind/56037325/',fallbackLabel:'Carte Outdooractive'},
  {key:'mannen',name:'Mannen',title:'Mannen (400m)',island:'Vestvågøy',altitude:'400 m',distance:'4,1 km aller-retour',duration:'~3 h',effort:'3/5',grade:'Modérée',crowd:'Fréquentée',caution:'Crête finale plus étroite et exposée; éviter par vent fort, pluie ou terrain glissant.',lat:68.199630,lon:13.532630,url:'https://lofotenhikes.com/hike/mannen-400m/',traceUrl:'https://lofotenhikes.com/hike/mannen-400m/#route-map',fallbackUrl:'https://visitlofoten.com/en/guide/mannen-400-m/',fallbackLabel:'Visit Lofoten'},
  {key:'haen',name:'Håen / Håheia',title:'Håen (Håheia) 438m',island:'Værøy',altitude:'438 m',distance:'5,7 km aller-retour',duration:'~3 h',effort:'2/5',grade:'Modérée, montée douce',crowd:'Modérée hors ferry de pointe',caution:'Værøy impose une traversée en ferry; rester très loin des falaises sommitales, particulièrement avec enfants ou chien.',lat:67.672383,lon:12.658083,url:'https://lofotenhikes.com/hike/haen-haheia-438m/',traceUrl:'https://lofotenhikes.com/hike/haen-haheia-438m/#route-map',fallbackUrl:'https://visitlofoten.com/en/activity/hiking/hike-to-haheia-at-vaeroy-438-m/',fallbackLabel:'Visit Lofoten'},
  {key:'hoven',name:'Hoven',title:'Hoven (367m) — panorama paisible',island:'Gimsøy',altitude:'367 m',distance:'3,8 km aller-retour',duration:'~2,5 h',effort:'2,5/5',grade:'Facile à modérée, non exposée',crowd:'Plutôt calme',caution:'Approche souvent humide et marécageuse; vérifier les conditions et le stationnement au golf avant le départ.',lat:68.339380,lon:14.113233,url:'https://lofotenhikes.com/hike/hoven-367m/',traceUrl:'https://lofotenhikes.com/hike/hoven-367m/#route-map',fallbackUrl:'https://visitlofoten.com/en/guide/hoven-367-m-a-sl/',fallbackLabel:'Visit Lofoten',quiet:true},
  {key:'nubben',name:'Nubben',title:'Nubben (240m) — balcon sur Ramberg',island:'Flakstadøy',altitude:'240 m',distance:'1,2 km aller-retour',duration:'~1 h',effort:'2/5',grade:'Courte mais raide',crowd:'Souvent calme',caution:'Montée et descente raides; terrain glissant après la pluie. S’arrêter à Nubben et ne pas poursuivre vers Moltinden sans expérience adaptée.',lat:68.086120,lon:13.236700,url:'https://lofotenhikes.com/hike/nubben-240m/',traceUrl:'https://lofotenhikes.com/hike/nubben-240m/#route-map',fallbackUrl:'https://www.outdooractive.com/en/route/hiking-trail/norway/ramberg-nubben-lofoten-/245895959/',fallbackLabel:'Carte Outdooractive',quiet:true},
  {key:'tuva',name:'Tuva',title:'Tuva (477m) — alternative à Fløya',island:'Austvågøy',altitude:'477 m',distance:'4 km aller-retour',duration:'~3 h',effort:'3/5',grade:'Modérée, crête finale',crowd:'Moins fréquentée que Fløya',caution:'Dernière crête étroite avec sensation d’exposition; boue et racines glissantes possibles. À éviter par vent fort.',lat:68.251500,lon:14.553500,url:'https://lofotenhikes.com/hike/tuva-477m/',traceUrl:'https://lofotenhikes.com/hike/tuva-477m/#route-map',fallbackUrl:'https://lofotenhikes.com/tag/tjeldbergtinden/',fallbackLabel:'Sélection locale',quiet:true},
  {key:'blatinden',name:'Blåtinden',title:'Blåtinden (621m) — grand sommet sauvage',island:'Austvågøy',altitude:'621 m',distance:'4,6 km aller-retour',duration:'~3–3,5 h',effort:'4/5',grade:'Soutenue, petit scrambling final',crowd:'Peu fréquentée',caution:'Final rocheux et exposé avec utilisation des mains; seulement par terrain sec, bonne visibilité et vent faible.',lat:68.255230,lon:14.580260,url:'https://lofotenhikes.com/hike/blatinden-612m/',traceUrl:'https://lofotenhikes.com/hike/blatinden-612m/#route-map',fallbackUrl:'https://www.wikiloc.com/hiking-trails/blatinden-55677599',fallbackLabel:'Trace Wikiloc',quiet:true},
  {key:'hornet',name:'Hornet',title:'Hornet (346m) — Værøy à 360°',island:'Værøy',altitude:'346 m',distance:'2,8 km aller-retour',duration:'~2 h',effort:'2,5/5',grade:'Modérée, courte',crowd:'Très calme',caution:'Accès dépendant du ferry; pentes raides et falaises proches du sommet. Garder Paddy en laisse et rester loin des rebords.',lat:67.680067,lon:12.649433,url:'https://lofotenhikes.com/hike/hornet-346m/',traceUrl:'https://lofotenhikes.com/hike/hornet-346m/#route-map',fallbackUrl:'https://rando-lofoten.net/index.php?Itemid=1258&id=541&lang=en&option=com_content&view=article',fallbackLabel:'Description + GPX',quiet:true},
  {key:'holandsmaelen',name:'Holandsmælen',title:'Holandsmælen (434m) — vue centrale à 360°',island:'Vestvågøy',altitude:'434 m',distance:'~5,5 km aller-retour',duration:'~3 h',effort:'2,5/5',grade:'Facile à modérée',crowd:'Plutôt calme',caution:'Sentier non balisé mais généralement visible; dernières pentes plus raides. Attention au brouillard et aux terrains humides.',lat:68.175920,lon:13.524620,url:'https://lofotenhikes.com/hike/holandsmaelen-434m/',traceUrl:'https://lofotenhikes.com/hike/holandsmaelen-434m/#route-map',fallbackUrl:'https://www.outdooractive.com/en/route/hiking-trail/lofoten/holandsmaelen/56037245/',fallbackLabel:'Carte Outdooractive',quiet:true}
];

function hikeSourceForName(name){const n=String(name||'').toLowerCase();return LOFOTEN_HIKES.find(h=>n.includes(h.key)||n.includes(h.name.toLowerCase().split(' / ')[0])||h.name.toLowerCase().includes(n))}
function hikeLinks(h){return `<a href="${h.url}" target="_blank" rel="noopener">Description ↗</a> · <a href="${h.traceUrl||h.url}" target="_blank" rel="noopener"><b>Voir le tracé 2D/3D ↗</b></a>${h.fallbackUrl?` · <a href="${h.fallbackUrl}" target="_blank" rel="noopener">${esc(h.fallbackLabel||'Alternative')} ↗</a>`:''}`}
function weatherIcon(code){if(code===0)return '☀️';if([1,2].includes(code))return '🌤️';if(code===3)return '☁️';if([45,48].includes(code))return '🌫️';if(code>=51&&code<=67)return '🌧️';if(code>=71&&code<=77)return '🌨️';if(code>=80&&code<=82)return '🌦️';if(code>=85&&code<=86)return '🌨️';if(code>=95)return '⛈️';return '🌥️'}
function weatherRisk(rain,wind,gust){if(gust>=65||wind>=45||rain>=15)return ['danger','À éviter'];if(gust>=45||wind>=30||rain>=7)return ['caution','Prudence'];return ['good','Plutôt favorable']}
function weatherDate(iso){return new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'}).format(new Date(`${iso}T12:00:00`))}
async function loadHikeWeather(key,targetId){const h=LOFOTEN_HIKES.find(x=>x.key===key),box=byId(targetId);if(!h||!box)return;box.innerHTML='<p class="status">Chargement de la météo locale…</p>';const params=new URLSearchParams({latitude:h.lat,longitude:h.lon,timezone:'auto',forecast_days:'7',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max'});try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`);if(!r.ok)throw Error();const d=await r.json(),x=d.daily;box.innerHTML=`<div class="weather-head"><b>Météo au départ de ${esc(h.name)}</b><small>Prévision 7 jours · mise à jour en direct</small></div><div class="weather-days">${x.time.map((date,i)=>{const rain=Math.round(x.precipitation_sum[i]||0),wind=Math.round(x.wind_speed_10m_max[i]||0),gust=Math.round(x.wind_gusts_10m_max[i]||0),risk=weatherRisk(rain,wind,gust);return `<article class="weather-day ${risk[0]}"><b>${weatherDate(date)}</b><span class="weather-symbol">${weatherIcon(x.weather_code[i])}</span><strong>${Math.round(x.temperature_2m_max[i])}° / ${Math.round(x.temperature_2m_min[i])}°</strong><small>🌧️ ${rain} mm · ${Math.round(x.precipitation_probability_max[i]||0)}%</small><small>💨 ${wind} km/h · raf. ${gust}</small><em>${risk[1]}</em></article>`}).join('')}</div><p class="weather-note">Prévision au point de départ. En altitude, le vent, le froid et la visibilité peuvent être sensiblement plus défavorables. Vérifier à nouveau le matin du départ.</p>`}catch(e){console.error(e);box.innerHTML='<p class="status">Prévision momentanément indisponible. Réessaie avec une connexion active.</p>'}}
function weatherButton(h,context){const id=`weather-${context}-${h.key}`;return `<button class="weather-toggle" data-hike-weather="${h.key}" data-weather-target="${id}">🌦️ Météo 7 jours</button><div id="${id}" class="hike-weather" hidden></div>`}
function bindWeatherButtons(){document.querySelectorAll('[data-hike-weather]').forEach(b=>b.onclick=()=>{const box=byId(b.dataset.weatherTarget);if(!box)return;box.hidden=!box.hidden;if(!box.hidden&&!box.dataset.loaded){box.dataset.loaded='1';loadHikeWeather(b.dataset.hikeWeather,b.dataset.weatherTarget)}})}
function hikeCard(h,planned=false){return `<article class="hike-card ${planned?'planned':''}"><div class="hike-card-head"><div><span class="hike-island">${esc(h.island)}</span><h3>${esc(h.title)}</h3></div>${planned?'<span class="hike-status">Planifiée</span>':h.quiet?'<span class="hike-status quiet">Pépite calme</span>':'<span class="hike-status alt">Alternative</span>'}</div><div class="hike-metrics"><span><b>${esc(h.distance)}</b><small>Distance</small></span><span><b>${esc(h.duration)}</b><small>Durée</small></span><span><b>${esc(h.altitude)}</b><small>Sommet</small></span><span><b>${esc(h.effort)}</b><small>Effort</small></span></div><p><b>${esc(h.grade)}</b> · <span>${esc(h.crowd||'Fréquentation variable')}</span></p><p class="muted">${esc(h.caution)}</p><div class="toolbar"><a class="btn" href="${h.url}" target="_blank" rel="noopener">Description ↗</a><a class="btn primary" href="${h.traceUrl||h.url}" target="_blank" rel="noopener">🗺️ Voir le tracé 2D/3D ↗</a>${h.fallbackUrl?`<a class="btn" href="${h.fallbackUrl}" target="_blank" rel="noopener">${esc(h.fallbackLabel||'Alternative')} ↗</a>`:''}${planned?`<button class="remove-hike" data-hike="${h.key}">Retirer du plan</button>`:`<button class="add-hike" data-hike="${h.key}">Ajouter au plan</button>`}</div>${weatherButton(h,'card')}</article>`}

function renderFamilyEnhanced(){
  const planned=LOFOTEN_HIKES.filter(h=>state.olivier.some(x=>hikeSourceForName(x[0])?.key===h.key));const alternatives=LOFOTEN_HIKES.filter(h=>!planned.some(p=>p.key===h.key));const quiet=alternatives.filter(h=>h.quiet);const classics=alternatives.filter(h=>!h.quiet);
  byId('app').innerHTML=`<section class="card"><h2>Activités famille — Sorya & Paddy en priorité</h2>${editableTable(state.activities,['Activité','Secteur','Catégorie','Durée','Terrain','Paddy','Latitude','Longitude'],'activities')}</section><section class="card hike-library"><div class="map-heading"><div><h2>Randonnées prévues — Olivier</h2><p class="muted">Description, tracé 2D/3D et météo locale à sept jours pour chaque randonnée.</p></div><div class="toolbar"><a class="btn" href="https://lofotenhikes.com/all-hikes/" target="_blank" rel="noopener">Toutes les randonnées ↗</a><a class="btn" href="https://lofotenhikes.com/map/" target="_blank" rel="noopener">Carte LofotenHikes ↗</a></div></div><div class="hike-grid">${planned.length?planned.map(h=>hikeCard(h,true)).join(''):'<p class="status">Aucune randonnée sportive planifiée.</p>'}</div></section><section class="card hike-library quiet-section"><h2>🌿 Pépites plus tranquilles</h2><p class="muted">Des panoramas majeurs, généralement loin des flux de Reinebringen, Ryten ou Festvågtinden. « Calme » reste relatif et dépend de l’heure, de la météo et de la saison.</p><div class="hike-grid">${quiet.map(h=>hikeCard(h,false)).join('')}</div></section><section class="card hike-library"><h2>Autres classiques et alternatives</h2><div class="hike-grid">${classics.map(h=>hikeCard(h,false)).join('')}</div></section>`;
  bindEditable('activities',renderFamilyEnhanced);bindWeatherButtons();
  document.querySelectorAll('.add-hike').forEach(button=>button.onclick=()=>{const h=LOFOTEN_HIKES.find(x=>x.key===button.dataset.hike);if(h&&!state.olivier.some(x=>hikeSourceForName(x[0])?.key===h.key))state.olivier.push([h.name,h.caution]);save();autoSync();renderFamilyEnhanced()});
  document.querySelectorAll('.remove-hike').forEach(button=>button.onclick=()=>{state.olivier=state.olivier.filter(x=>hikeSourceForName(x[0])?.key!==button.dataset.hike);save();autoSync();renderFamilyEnhanced()});
}

function showHikingMapEnhanced(){
  byId('hike-view').classList.add('primary');byId('road-view').classList.remove('primary');baseMap([68.08,13.45],9,true);const bounds=[];
  state.activities.forEach((a,i)=>{const lat=Number(a[6]),lon=Number(a[7]);if(Number.isFinite(lat)&&Number.isFinite(lon)){bounds.push([lat,lon]);const source=hikeSourceForName(a[0]);const link=source?`<br>${hikeLinks(source)}`:'';L.marker([lat,lon],{icon:numberedIcon(i+1,'hike')}).addTo(leafletMap).bindPopup(`<b>${esc(a[0])}</b><br>${esc(a[2])} · ${esc(a[3])}<br>${esc(a[4])}<br>Paddy : ${esc(a[5])}${link}`)}});
  const plannedKeys=new Set(state.olivier.map(x=>hikeSourceForName(x[0])?.key).filter(Boolean));
  LOFOTEN_HIKES.forEach(h=>{bounds.push([h.lat,h.lon]);const planned=plannedKeys.has(h.key),marker=planned?'🥾':h.quiet?'🌿':'○',popupId=`weather-popup-${h.key}`;L.marker([h.lat,h.lon],{icon:L.divIcon({className:'numbered-marker hike',html:`<span>${marker}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}).addTo(leafletMap).bindPopup(`<b>${esc(h.title)}</b><br>${esc(h.island)} · ${esc(h.distance)} · ${esc(h.duration)}<br>${esc(h.grade)} · <b>${esc(h.crowd||'Fréquentation variable')}</b><br><span class="muted">${esc(h.caution)}</span><br>${hikeLinks(h)}<br><button class="weather-toggle popup-weather" data-hike-weather="${h.key}" data-weather-target="${popupId}">🌦️ Afficher la météo 7 jours</button><div id="${popupId}" class="hike-weather popup-forecast" hidden></div>`)});
  leafletMap.on('popupopen',()=>bindWeatherButtons());
  if(state.gps.points.length>1){const pts=state.gps.points.map(p=>[p.lat,p.lon]);L.polyline(pts,{weight:4}).addTo(leafletMap);bounds.push(...pts)}
  if(bounds.length)leafletMap.fitBounds(bounds,{padding:[25,25],maxZoom:11});
  byId('map-summary').innerHTML=`<div><strong>${state.activities.length}</strong><span>activités familiales</span></div><div><strong>${LOFOTEN_HIKES.filter(h=>h.quiet).length}</strong><span>pépites plus calmes</span></div><div><strong>${LOFOTEN_HIKES.length}</strong><span>randonnées documentées</span></div>`;
  byId('route-status').textContent='Clique sur une randonnée pour consulter le tracé et sa météo locale à sept jours.';
  byId('map-legend').innerHTML='<span><i class="dot-hike"></i>Activités famille</span><span>🥾 planifiée · 🌿 pépite calme · ○ autre alternative</span><a target="_blank" rel="noopener" href="https://lofotenhikes.com/map/">Carte LofotenHikes ↗</a>';
}

renderFamily=renderFamilyEnhanced;
showHikingMap=showHikingMapEnhanced;
