'use strict';

(function initNightlyOptions(){
  const P=(id)=>`https://park4night.com/fr/place/${id}`;
  const NIGHTS={
    '25/08':{date:'25/08',label:'Nuit 1 · 25 août',route:'Chevreuse → nord de l’Allemagne',preferred:{name:'Park4Night #53279',url:P('53279'),role:'Choix confirmé',status:'preferred'},alternatives:[{name:'Park4Night #417435',url:P('417435'),role:'Alternative 1',status:'alternative'},{name:'Park4Night #453901',url:P('453901'),role:'Alternative 2',status:'alternative'}]},
    '26/08':{date:'26/08',label:'Nuit 2 · 26 août',route:'Nord Allemagne → sud Suède',preferred:{name:'Park4Night #84058',url:P('84058'),role:'Choix confirmé',status:'preferred'},alternatives:[{name:'Park4Night #698010',url:P('698010'),role:'Alternative 1',status:'alternative'},{name:'Park4Night #391481',url:P('391481'),role:'Alternative 2',status:'alternative'}]},
    '27/08':{date:'27/08',label:'Nuit 3 · 27 août',route:'Sud Suède → région de Gävle',preferred:{name:'Forsgården · Park4Night #188958',url:P('188958'),role:'Choix confirmé',status:'preferred'},alternatives:[{name:'Park4Night #214874',url:P('214874'),role:'Alternative 1',status:'alternative'},{name:'Park4Night #76491',url:P('76491'),role:'Alternative 2',status:'alternative'}]},
    '28/08':{date:'28/08',label:'Nuit 4 · 28 août',route:'Gävle → nord de la Suède',preferred:{name:'Park4Night #140798',url:P('140798'),role:'Choix confirmé',status:'preferred'},alternatives:[{name:'Park4Night #260263',url:P('260263'),role:'Alternative 1',status:'alternative'},{name:'Park4Night #698541',url:P('698541'),role:'Alternative 2',status:'alternative'}]},
    '29/08':{date:'29/08',label:'Nuit 5 · 29 août',route:'Nord Suède → Abisko',preferred:{name:'Abisko Mountain Lodge',url:'https://www.abiskomountainlodge.se/',role:'Choix confirmé · lodge',status:'preferred'},alternatives:[{name:'Park4Night #133328',url:P('133328'),role:'Alternative 1',status:'alternative'},{name:'Park4Night #88528',url:P('88528'),role:'Alternative 2',status:'alternative'}]},
    '30/08':{date:'30/08',label:'Nuit 6 · 30 août',route:'Abisko → Gimsøy, Lofoten',preferred:{name:'Hov Camping',url:'https://hovgard.no/en/camping-caravanning/',role:'Plage arctique · services complets',status:'preferred'},alternatives:[{name:'Sandsletta Camping',url:'https://sandsletta.no/',role:'Alternative nature et fjord',status:'alternative'},{name:'Kabelvåg Feriehus & Camping',url:P('84297'),role:'Alternative services',status:'alternative'}]},
    '31/08':{date:'31/08',label:'Nuit 7 · 31 août',route:'Base Lofoten Est',preferred:{name:'Hov Camping',url:'https://hovgard.no/en/camping-caravanning/',role:'Seconde nuit sans refaire le camp',status:'preferred'},alternatives:[{name:'Sandsletta Camping',url:'https://sandsletta.no/',role:'Alternative météo Est',status:'alternative'},{name:'Kabelvåg Feriehus & Camping',url:P('84297'),role:'Alternative pratique',status:'alternative'}]},
    '01/09':{date:'01/09',label:'Nuit 8 · 1 septembre',route:'Gimsøy → Uttakleiv',preferred:{name:'Uttakleiv · Park4Night #38914',url:P('38914'),role:'Nuit signature du voyage',status:'preferred'},alternatives:[{name:'Haukland Beach area',url:'https://visitlofoten.com/en/topic/haukland-beach/',role:'Alternative plage voisine',status:'alternative'},{name:'Unstad Arctic Surf',url:'https://www.unstadarcticsurf.com/',role:'Alternative océan et surf',status:'alternative'}]},
    '02/09':{date:'02/09',label:'Nuit 9 · 2 septembre',route:'Uttakleiv → Flakstad',preferred:{name:'Lofoten Beach Camp · Skagsanden',url:'https://www.lofotenbeachcamp.no/',role:'Camping directement sur la plage',status:'preferred'},alternatives:[{name:'Ramberg Gjestegård',url:'https://ramberg-gjestegard.no/',role:'Alternative plage et services',status:'alternative'},{name:'Vikten · Park4Night #60765',url:P('60765'),role:'Alternative sauvage · vérifier le vent',status:'alternative'}]},
    '03/09':{date:'03/09',label:'Nuit 10 · 3 septembre',route:'Flakstad → Moskenes',preferred:{name:'Moskenes Camping',url:'https://moskenescamping.no/',role:'Balcon sur le Vestfjord',status:'preferred'},alternatives:[{name:'Reine Rorbuer / parking local',url:'https://visitlofoten.com/en/reine/',role:'Alternative proche de Reine',status:'alternative'},{name:'Sørvågen Camping',url:'https://www.google.com/maps/search/camping+Sørvågen+Norway',role:'Alternative au sud',status:'alternative'}]},
    '04/09':{date:'04/09',label:'Nuit 11 · 4 septembre',route:'Moskenes → ferry Bodø → Saltstraumen',preferred:{name:'Pluscamp Saltstraumen Camping',url:'https://saltstraumen-camping.no/',role:'Retour par la Norvège · phénomène naturel majeur',status:'preferred'},alternatives:[{name:'Lundhøgda Camping · Fauske',url:'https://www.lcamp.no/en/',role:'Alternative calme avec vue sur le fjord',status:'alternative'},{name:'Fauske Camping & Motell',url:'https://camping.no/en/campingplasser/1964846',role:'Alternative directement sur l’axe E6',status:'alternative'}]},
    '05/09':{date:'05/09',label:'Nuit 12 · 5 septembre',route:'Saltstraumen → Mosjøen',preferred:{name:'Topcamp Mosjøen',url:'https://topcamp.no/en/topcamp-mosjoen',role:'Étape E6 pratique au pied des montagnes',status:'preferred'},alternatives:[{name:'Korgen Camping',url:'https://korgen-camping.no/',role:'Alternative paisible au bord de la Røssåga',status:'alternative'},{name:'Baågneset Bobilparkering',url:'https://campio.no/campsite/baagneset-grendehus-bobilparkering',role:'Alternative camping-car près de Mosjøen',status:'alternative'}]},
    '06/09':{date:'06/09',label:'Nuit 13 · 6 septembre',route:'Mosjøen → région de Trondheim',preferred:{name:'Øysand Camping',url:'https://oysandcamping.no/',role:'Plage de sable · ouvert toute l’année · près de l’E6',status:'preferred'},alternatives:[{name:'Tråsåvika Camping',url:'https://trasavika.no/en/home',role:'Alternative fjord ouverte jusqu’au 20 septembre',status:'alternative'},{name:'Dora Bobilplass · Trondheim',url:'https://visittrondheim.no/overnatting/camping/bobilparkering/',role:'Alternative urbaine avec eau et vidange',status:'alternative'}]},
    '07/09':{date:'07/09',label:'Nuit 14 · 7 septembre',route:'Trondheim → Lillehammer',preferred:{name:'Lillehammer Camping',url:'https://lillehammer-camping.no/',role:'Au bord du lac Mjøsa · ouvert toute l’année',status:'preferred'},alternatives:[{name:'Hunderfossen Camping',url:'https://www.lillehammer.com/overnatting/hunderfossen-camping-p632043',role:'Alternative dans la vallée',status:'alternative'},{name:'Evjua Strandpark',url:'https://www.evjua.no/en-camping',role:'Alternative au bord du lac Mjøsa',status:'alternative'}]},
    '08/09':{date:'08/09',label:'Nuit 15 · 8 septembre',route:'Lillehammer → Larvik → ferry Hirtshals',preferred:{name:'Hirtshals Camping',url:'https://hirtshals-camping.dk/en/camping-en/',role:'Nuit après la traversée courte depuis la Norvège',status:'preferred'},alternatives:[{name:'Tornby Strand Camping',url:'https://www.google.com/maps/search/Tornby+Strand+Camping',role:'Alternative plage au sud de Hirtshals',status:'alternative'},{name:'Hirtshals Autocamperplads',url:'https://www.google.com/maps/search/Hirtshals+autocamperplads',role:'Alternative de transit tardif',status:'alternative'}]},
    '09/09':{date:'09/09',label:'Nuit 16 · 9 septembre',route:'Hirtshals → Münster',preferred:{name:'Campingplatz Münster',url:'https://www.campingplatz-muenster.de/',role:'Dernière nuit en route · ouvert en septembre',status:'preferred'},alternatives:[{name:'Reisemobilstellplatz Münster',url:'https://www.google.com/maps/search/Reisemobilstellplatz+Münster',role:'Alternative camping-car plus directe',status:'alternative'},{name:'Campingpark Münsterland Eichenhof',url:'https://www.google.com/maps/search/Campingpark+Münsterland+Eichenhof',role:'Alternative nature à l’ouest de Münster',status:'alternative'}]},
    '10/09':{date:'10/09',label:'Nuit 17 · 10 septembre',route:'Münster → domicile à Chevreuse',preferred:{name:'Maison · Chevreuse',url:'https://www.google.com/maps/search/Chevreuse+France',role:'ARRIVÉE OBLIGATOIRE, même tardive',status:'preferred'},alternatives:[{name:'Aucune alternative planifiée',url:'https://www.google.com/maps/search/Chevreuse+France',role:'Objectif impératif : dormir à la maison',status:'alternative'},{name:'Aucune nuit en route',url:'https://www.google.com/maps/search/Chevreuse+France',role:'Continuer jusqu’à Chevreuse',status:'alternative'}]}
  };

  function seed(){
    if(typeof state==='undefined')return;
    state.nightlyOptions=JSON.parse(JSON.stringify(NIGHTS));
    state.savedCamperStops=[];
    Object.values(NIGHTS).forEach((night,nightIndex)=>{
      const all=[night.preferred,...night.alternatives];
      all.forEach((option,i)=>state.savedCamperStops.push({name:`${night.date} · ${option.name}`,source:option.url.includes('park4night')?'Park4Night':'Site externe',url:option.url,reference:`night-${night.date}-${i}`,stopIndex:nightIndex,status:i===0?'selected':'backup',priority:i===0?'night-preferred':`night-alternative-${i}`,date:night.date,notes:option.role}));
    });
    if(typeof save==='function')save();
  }

  function optionCard(option,index){const preferred=option.status==='preferred';const linkLabel=option.url.includes('park4night.com')?'Ouvrir Park4Night ↗':'Ouvrir ↗';return `<article class="night-choice ${preferred?'preferred-choice':'alternative-choice'}"><div class="night-choice-rank">${preferred?'⭐ PRÉFÉRÉ':'ALT. '+index}</div><h4>${esc(option.name)}</h4><p>${esc(option.role)}</p><a class="btn ${preferred?'primary':''}" href="${esc(option.url)}" target="_blank" rel="noopener">${linkLabel}</a></article>`}
  function panelHtml(){const nights=Object.values(state.nightlyOptions||{}).sort((a,b)=>a.date.split('/').reverse().join('').localeCompare(b.date.split('/').reverse().join('')));return `<section class="card nightly-options-panel"><div class="nightly-options-heading"><div><p class="eyebrow">NUITS 2026 · RETOUR PAR LA NORVÈGE</p><h2>Préféré + deux alternatives</h2></div><p class="muted">Moskenes–Bodø, E6 vers Trondheim et Lillehammer, puis ferry Larvik–Hirtshals.</p></div>${nights.map(n=>`<div class="night-choice-day"><div class="night-choice-day-head"><h3>${esc(n.label)}</h3><span>${esc(n.route)}</span></div><div class="night-choice-grid">${optionCard(n.preferred,0)}${n.alternatives.map((o,i)=>optionCard(o,i+1)).join('')}</div></div>`).join('')}</section>`}
  function install(){seed();if(typeof renderItinerary!=='function')return;const base=window.renderItinerary;window.renderItinerary=function(){base();const app=document.getElementById('app');if(app)app.insertAdjacentHTML('afterbegin',panelHtml());}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();