'use strict';

(function seedPotentialStops(){
  const candidates=[
    {name:'Park4Night #664943 — première nuit · Alveslohe',source:'Park4Night',url:'https://park4night.com/fr/place/664943',reference:'664943',stopIndex:0,status:'selected',priority:'first-night',previousStage:'Saint-Rémy-lès-Chevreuse',distanceFromPrevious:'≈ 900 km',driveTimeFromPrevious:'≈ 9 h 30 à 10 h 30 hors pauses',notes:'Nouveau spot retenu pour la première nuit : grand parking gratuit près de la piscine extérieure à Alveslohe, annoncé calme et proche de l’A7. Attention : la fiche Park4Night le classe « parking jour uniquement » ; vérifier impérativement la signalisation et l’autorisation de nuit à l’arrivée.',services:['Gratuit','25 places annoncées','Ouvert toute l’année','Proche A7','Poubelles et sacs pour chiens signalés','Piscine extérieure à proximité'],lat:53.7830,lon:9.9179},
    {name:'Park4Night #359873 — deuxième nuit · Vätterledens Camping',source:'Park4Night',url:'https://park4night.com/fr/place/359873',reference:'359873',stopIndex:1,status:'selected',priority:'second-night',previousStage:'Alveslohe — Park4Night #664943',distanceFromPrevious:'≈ 640 km',driveTimeFromPrevious:'≈ 7 h 30 à 8 h 30 hors pauses et attente éventuelle au ferry',notes:'Spot retenu pour la deuxième nuit : Vätterledens Camping à Vättersmålen, près du lac Vättern et de Gränna. La fiche annonce une fermeture au 15 août : notre passage étant prévu le 26 août, il faut impérativement confirmer l’ouverture et conserver un plan B.',services:['Animaux autorisés','Eau potable','Toilettes','Douches','Électricité possible','Laverie','Baignade et randonnées à proximité','60 places annoncées'],price:'220 SEK annoncés pour le camping-car + 40 SEK pour l’électricité',openingWarning:'Fermeture annoncée au 15 août — à confirmer pour le 26 août 2026',rating:'4,08/5',lat:57.9250,lon:14.3221},
    {name:'Park4Night #188958 — troisième nuit · Forsgården',source:'Park4Night',url:'https://park4night.com/fr/place/188958',reference:'188958',stopIndex:2,status:'selected',priority:'third-night',previousStage:'Vätterledens Camping — Park4Night #359873',distanceFromPrevious:'≈ 435 km',driveTimeFromPrevious:'≈ 5 h 30 à 6 h hors pauses',notes:'Petite aire privée calme au bord de la rivière, à environ 5 km de Gävle. Douze emplacements seulement : appeler avant l’arrivée. Prévoir une protection contre les moustiques.',services:['Animaux autorisés','Eau potable','Vidange eaux noires','Poubelles','Toilettes','Douches','Électricité possible','Laverie','Cuisine et espace commun','Baignade dans la rivière'],price:'Environ 300 SEK ; confirmer',bookingWarning:'Appeler avant l’arrivée : 12 emplacements seulement',rating:'4,85/5',lat:60.6747,lon:17.0740},
    {name:'Park4Night #293420 — quatrième étape · plage de Stöcksjö, Umeå',source:'Park4Night',url:'https://park4night.com/fr/place/293420',reference:'293420',stopIndex:3,status:'selected-with-warning',priority:'fourth-night-review',previousStage:'Forsgården — Park4Night #188958',distanceFromPrevious:'≈ 500 km',driveTimeFromPrevious:'≈ 5 h 45 à 6 h 30 hors pauses',notes:'Spot au bord de l’eau à Stöcksjö, au sud d’Umeå. Park4Night classe officiellement ce lieu « parking jour uniquement » et les avis sont contradictoires concernant la nuit. Vérifier la signalisation et prévoir un plan B autorisé.',services:['Animaux autorisés','Poubelles','Toilettes publiques','Baignade','Aire de jeux','Activités nautiques','Ouvert toute l’année'],price:'20 SEK par jour annoncés',overnightWarning:'Nuit non garantie et possiblement interdite',rating:'4/5',lat:63.7752,lon:20.1949},
    {name:'Park4Night #696328 — option Abisko si nous ne restons pas au lodge',source:'Park4Night',url:'https://park4night.com/fr/place/696328',reference:'696328',stopIndex:4,status:'conditional',priority:'abisko-lodge-alternative',previousStage:'Stöcksjö, Umeå — Park4Night #293420',distanceFromPrevious:'≈ 690 km',driveTimeFromPrevious:'≈ 8 h à 8 h 45 hors pauses',notes:'Option de nuit à Abisko uniquement si nous ne restons pas au lodge. Vérifier sur la fiche les conditions d’accès, la signalisation, la capacité réelle et les avis récents avant de s’y installer. Conserver un plan B autour d’Abisko.',services:['Option alternative au lodge','À vérifier avant arrivée'],price:'À vérifier',lodgeAlternative:true,lat:'',lon:''},
    {name:'Park4Night #121761 — étape suivante · Camping Lofoten Feriensenter, Svolvær',source:'Park4Night',url:'https://park4night.com/fr/place/121761',reference:'121761',stopIndex:5,status:'selected-with-reservation-warning',priority:'svolvaer-camping',previousStage:'Abisko — Park4Night #696328 ou Abisko Mountain Lodge',distanceFromPrevious:'≈ 286 km',driveTimeFromPrevious:'≈ 4 h à 4 h 30 hors pauses',notes:'Camping à Svolvær avec emplacements asphaltés, sanitaires, électricité et laverie. Seulement 13 places et avis très contrastés : contacter le camping avant l’arrivée. Attention aux ralentisseurs non signalés sur la route d’accès et au supplément chien signalé dans un avis.',services:['Animaux autorisés','Eau potable','Vidange eaux noires','Poubelles','Toilettes','Douches','Électricité','Wi-Fi','Laverie'],price:'450 NOK avec électricité pour 2 personnes annoncé',bookingWarning:'13 places seulement — confirmer la disponibilité',rating:'2,69/5',lat:68.2480,lon:14.5487},
    {name:'Park4Night #84297 — étape suivante · Kabelvåg Feriehus & Camping',source:'Park4Night',url:'https://park4night.com/fr/place/84297',reference:'84297',stopIndex:6,status:'selected',priority:'kabelvag-camping',previousStage:'Camping Lofoten Feriensenter, Svolvær — Park4Night #121761',distanceFromPrevious:'≈ 7 km',driveTimeFromPrevious:'≈ 10 à 15 min',notes:'Camping bien équipé à Kabelvåg, pratique pour refaire les services, prendre une douche chaude, laver le linge et démarrer plusieurs randonnées. Les avis signalent un site globalement propre et calme, mais peu de sanitaires lorsque le camping est complet et un peu de bruit possible depuis l’E10.',services:['Animaux autorisés','Eau potable','Vidange eaux noires','Vidange eaux grises','Poubelles','Toilettes','Douches','Électricité','Wi-Fi','Laverie','Cuisine'],price:'430 NOK hors électricité annoncé ; électricité 50 NOK, douche chaude 10 NOK',openingInfo:'Ouvert toute l’année',rating:'4,2/5 sur 122 avis',lat:68.2171,lon:14.4474},
    {name:'Park4Night #697122 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/697122',reference:'697122',stopIndex:7,status:'selected-pending-details',priority:'next-stage',previousStage:'Kabelvåg — Park4Night #84297',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape ajoutée dans l’ordre du voyage. Détails et coordonnées à vérifier sur la fiche Park4Night.',services:['À vérifier'],price:'À vérifier',lat:'',lon:''},
    {name:'Park4Night #81739 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/81739',reference:'81739',stopIndex:8,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #697122',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape ajoutée dans l’ordre du voyage. Détails, accès, services et avis récents à vérifier sur la fiche Park4Night.',services:['À vérifier'],price:'À vérifier',lat:'',lon:''},
    {name:'Park4Night #610111 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/610111',reference:'610111',stopIndex:9,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #81739',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape ajoutée dans l’ordre du voyage. Vérifier en priorité les conditions d’accès avec un camping-car de 3,01 m de haut, ainsi que l’autorisation de nuit et les avis récents.',services:['À vérifier'],price:'À vérifier',vehicleHeightCheck:true,lat:'',lon:''},
    {name:'Park4Night #698111 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/698111',reference:'698111',stopIndex:10,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #610111',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape ajoutée dans l’ordre du voyage. Vérifier les coordonnées, l’accès, l’autorisation de nuit, les services et les avis récents.',services:['À vérifier'],price:'À vérifier',lat:'',lon:''},
    {name:'Park4Night #582192 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/582192',reference:'582192',stopIndex:11,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #698111',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape ajoutée dans l’ordre du voyage. Vérifier les coordonnées, l’accès, l’autorisation de nuit, les services disponibles et les avis récents.',services:['À vérifier'],price:'À vérifier',lat:'',lon:''},
    {name:'Park4Night #697896 — ancien premier arrêt potentiel',source:'Park4Night',url:'https://park4night.com/fr/place/697896',reference:'697896',stopIndex:0,status:'backup',priority:'review',notes:'Ancienne option pour la première nuit, conservée comme solution de secours.',lat:'',lon:''},
    {name:'Park4Night #347908 — ancienne option deuxième nuit',source:'Park4Night',url:'https://park4night.com/fr/place/347908',reference:'347908',stopIndex:1,status:'backup',priority:'review',notes:'Ancienne option pour la deuxième nuit.',lat:'',lon:''},
    {name:'Park4Night #565906 — ancienne option troisième nuit',source:'Park4Night',url:'https://park4night.com/fr/place/565906',reference:'565906',stopIndex:2,status:'backup',priority:'efficient',notes:'Ancienne option pour la troisième nuit.',lat:'',lon:''},
    {name:'Park4Night #153403 — option de secours quatrième étape',source:'Park4Night',url:'https://park4night.com/fr/place/153403',reference:'153403',stopIndex:3,status:'backup',priority:'efficient',notes:'Option de secours pour la quatrième étape.',lat:'',lon:''}
  ];

  if(typeof state==='undefined')return;
  if(!Array.isArray(state.savedCamperStops))state.savedCamperStops=[];
  let changed=false;
  const managed=['664943','359873','188958','293420','696328','121761','84297','697122','81739','610111','698111','582192','347908','565906','153403'];
  candidates.forEach(candidate=>{
    const index=state.savedCamperStops.findIndex(stop=>String(stop.reference||'').includes(candidate.reference)||String(stop.url||'').includes(`/place/${candidate.reference}`));
    if(index<0){state.savedCamperStops.push(candidate);changed=true;}
    else if(managed.includes(candidate.reference)){state.savedCamperStops[index]=Object.assign({},state.savedCamperStops[index],candidate);changed=true;}
  });
  if(changed&&typeof save==='function')save();
})();