'use strict';

(function seedPotentialStops(){
  const candidates=[
    {name:'Park4Night #664943 — première nuit · Alveslohe',source:'Park4Night',url:'https://park4night.com/fr/place/664943',reference:'664943',stopIndex:0,status:'selected',priority:'first-night',previousStage:'Saint-Rémy-lès-Chevreuse',distanceFromPrevious:'≈ 900 km',driveTimeFromPrevious:'≈ 9 h 30 à 10 h 30 hors pauses',notes:'Grand parking gratuit près de la piscine extérieure à Alveslohe, annoncé calme et proche de l’A7. La fiche le classe toutefois « parking jour uniquement » : vérifier impérativement la signalisation et l’autorisation de nuit à l’arrivée.',services:['Gratuit','25 places annoncées','Ouvert toute l’année','Proche A7','Poubelles et sacs pour chiens signalés'],lat:53.7830,lon:9.9179},
    {name:'Park4Night #359873 — deuxième nuit · Vätterledens Camping',source:'Park4Night',url:'https://park4night.com/fr/place/359873',reference:'359873',stopIndex:1,status:'selected-with-warning',priority:'second-night',previousStage:'Alveslohe — Park4Night #664943',distanceFromPrevious:'≈ 640 km',driveTimeFromPrevious:'≈ 7 h 30 à 8 h 30 hors pauses et attente éventuelle au ferry',notes:'Camping naturel près du lac Vättern. La fiche annonce une fermeture au 15 août : confirmer impérativement l’ouverture pour notre passage et conserver un plan B.',services:['Animaux autorisés','Eau potable','Toilettes','Douches','Électricité possible','Laverie','Baignade'],price:'220 SEK + 40 SEK électricité annoncés',openingWarning:'Ouverture après le 15 août à confirmer',lat:57.9250,lon:14.3221},
    {name:'Park4Night #188958 — troisième nuit · Forsgården',source:'Park4Night',url:'https://park4night.com/fr/place/188958',reference:'188958',stopIndex:2,status:'selected',priority:'third-night',previousStage:'Vätterledens Camping — Park4Night #359873',distanceFromPrevious:'≈ 435 km',driveTimeFromPrevious:'≈ 5 h 30 à 6 h hors pauses',notes:'Petite aire privée calme au bord de la rivière près de Gävle. Douze emplacements seulement : appeler avant l’arrivée. Très adaptée à une promenade avec Paddy.',services:['Animaux autorisés','Eau potable','Vidange eaux noires','Toilettes','Douches','Électricité','Laverie','Cuisine commune'],price:'Environ 300 SEK ; confirmer',bookingWarning:'Appeler avant l’arrivée',lat:60.6747,lon:17.0740},

    {name:'Park4Night #136201 — étape Umeå retenue · aire officielle avec vue',source:'Park4Night',url:'https://park4night.com/fr/place/136201',reference:'136201',stopIndex:3,status:'selected',priority:'umea-legal-scenic-replacement',previousStage:'Forsgården — Park4Night #188958',distanceFromPrevious:'≈ 500 km',driveTimeFromPrevious:'≈ 5 h 45 à 6 h 30 hors pauses',notes:'Remplace la plage de Stöcksjö, dont l’autorisation de nuit est contradictoire. Aire signalée comme emplacement officiel pour camping-cars sur la plateforme supérieure, avec belle vue, foyer, table de pique-nique et toilette sèche. Un bruit ponctuel de corne ou de train a été signalé la nuit.',services:['Gratuit','Emplacement officiel signalé','Toilette sèche','Tables de pique-nique','Foyer','Belle vue'],price:'Gratuit annoncé',rating:'3,43/5',lat:63.8767,lon:20.0187},
    {name:'Park4Night #293420 — Stöcksjö · ancienne option écartée',source:'Park4Night',url:'https://park4night.com/fr/place/293420',reference:'293420',stopIndex:3,status:'rejected',priority:'overnight-legality-risk',notes:'Écarté de l’itinéraire principal : la fiche est classée « parking jour uniquement » et les avis se contredisent sur l’autorisation de passer la nuit.',overnightWarning:'Ne pas utiliser comme nuit planifiée',lat:63.7752,lon:20.1949},

    {name:'Park4Night #696328 — option Abisko si nous ne restons pas au lodge',source:'Park4Night',url:'https://park4night.com/fr/place/696328',reference:'696328',stopIndex:4,status:'conditional',priority:'abisko-lodge-alternative',previousStage:'Umeå — Park4Night #136201',distanceFromPrevious:'≈ 690 km',driveTimeFromPrevious:'≈ 8 h à 8 h 45 hors pauses',notes:'Option uniquement si nous ne restons pas au lodge. Vérifier l’accès, la signalisation et les avis récents avant de s’installer.',services:['Alternative au lodge','À vérifier'],lodgeAlternative:true,lat:'',lon:''},

    {name:'Park4Night #121761 — Svolvær · option de secours/services',source:'Park4Night',url:'https://park4night.com/fr/place/121761',reference:'121761',stopIndex:5,status:'backup',priority:'service-only',previousStage:'Abisko',notes:'Conservé seulement comme solution de secours ou de services. Peu de places et avis très contrastés ; ne constitue plus notre nuit Lofoten privilégiée.',services:['Eau','Vidange','Sanitaires','Douches','Électricité','Wi-Fi','Laverie'],rating:'2,69/5',lat:68.2480,lon:14.5487},
    {name:'Park4Night #84297 — Kabelvåg · nuit de services',source:'Park4Night',url:'https://park4night.com/fr/place/84297',reference:'84297',stopIndex:5,status:'selected',priority:'lofoten-service-night',previousStage:'Abisko — lodge ou #696328',distanceFromPrevious:'≈ 290 km',driveTimeFromPrevious:'≈ 4 h à 4 h 45 hors pauses',notes:'Camping retenu pour une seule nuit pratique : douche, lessive, eau, vidanges et recharge avant une nuit beaucoup plus spectaculaire sur la côte ouest des Lofoten.',services:['Animaux autorisés','Eau potable','Eaux noires et grises','Toilettes','Douches','Électricité','Wi-Fi','Laverie','Cuisine'],price:'430 NOK hors électricité annoncé ; électricité 50 NOK',lat:68.2171,lon:14.4474},
    {name:'Park4Night #38914 — Uttakleiv · nuit panoramique des Lofoten',source:'Park4Night',url:'https://park4night.com/fr/place/38914',reference:'38914',stopIndex:6,status:'selected',priority:'lofoten-scenic-night',previousStage:'Kabelvåg — Park4Night #84297',distanceFromPrevious:'≈ 55 km',driveTimeFromPrevious:'≈ 1 h à 1 h 15',notes:'Remplace une deuxième nuit urbaine autour de Svolvær/Kabelvåg. Emplacement directement à Uttakleiv, au bord de la plage et des montagnes, avec départ de la marche côtière vers Haukland. Endroit très fréquenté en journée mais généralement plus calme le soir. Pas de vidange des eaux grises.',services:['Animaux autorisés','Eau potable','Vidange cassette','Poubelles','Toilettes','Randonnées','Plage','Point de vue'],price:'Environ 300 NOK/24 h annoncé',rating:'3,43/5 sur près de 200 avis',lat:68.2091,lon:13.5067},

    {name:'Park4Night #697122 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/697122',reference:'697122',stopIndex:7,status:'selected-pending-details',priority:'next-stage',previousStage:'Uttakleiv — Park4Night #38914',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape conservée dans l’ordre du voyage ; détails à compléter.',services:['À vérifier'],lat:'',lon:''},
    {name:'Park4Night #84431 — Saltstraumen Camping · remplacement de Fauske',source:'Park4Night',url:'https://park4night.com/fr/place/84431',reference:'84431',stopIndex:8,status:'selected',priority:'saltstraumen-replacement',previousStage:'Park4Night #697122',distanceFromPrevious:'À calculer selon le point précédent',driveTimeFromPrevious:'À calculer',notes:'Remplace la nuit peu convaincante près de Fauske. Camping ouvert toute l’année à proximité immédiate de Saltstraumen, permettant de voir le puissant courant de marée et de démarrer la route côtière 17 dans de bonnes conditions. Option plus chère mais sûre, équipée et adaptée au camping-car.',services:['Eau potable','Vidange','Sanitaires chauffés','Douches','Électricité','Wi-Fi','Laverie'],price:'Environ 465 NOK annoncé',rating:'4,14/5',lat:67.2354,lon:14.6207},
    {name:'Park4Night #81739 — Fauske · option écartée',source:'Park4Night',url:'https://park4night.com/fr/place/81739',reference:'81739',stopIndex:8,status:'rejected',priority:'poor-recent-reviews',notes:'Écarté au profit de Saltstraumen : les retours récents sur l’entretien et les sanitaires ne justifient pas d’y consacrer une nuit.',lat:'',lon:''},
    {name:'Park4Night #23954 — Storvika · plage sur la route Helgelandskysten',source:'Park4Night',url:'https://park4night.com/fr/place/23954',reference:'23954',stopIndex:9,status:'selected',priority:'helgeland-scenic-route',previousStage:'Saltstraumen — Park4Night #84431',distanceFromPrevious:'≈ 115 km par la route 17',driveTimeFromPrevious:'≈ 2 h hors arrêts panoramiques et ferry éventuel',notes:'Étape panoramique choisie sur la route côtière Helgelandskysten : plage, montagnes, toilettes propres, eau, vidange cassette, tables et petit commerce. La route 17 doit être parcourue sans précipitation et les horaires de ferry devront être vérifiés.',services:['Animaux autorisés','Eau potable','Vidange cassette','Poubelles','Toilettes','Plage','Tables de pique-nique','Commerce proche'],price:'Gratuit annoncé',rating:'4,47/5',lat:66.9600,lon:13.8032},
    {name:'Park4Night #610111 — étape supprimée · hauteur incompatible',source:'Park4Night',url:'https://park4night.com/fr/place/610111',reference:'610111',stopIndex:9,status:'rejected-inaccessible',priority:'vehicle-height-conflict',notes:'Supprimé de l’itinéraire : restriction de hauteur signalée à 2,8 m, incompatible avec notre camping-car d’environ 3,01 m.',vehicleHeightLimit:'2,8 m',vehicleHeight:'3,01 m',lat:'',lon:''},

    {name:'Park4Night #698111 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/698111',reference:'698111',stopIndex:10,status:'selected-pending-details',priority:'next-stage',previousStage:'Storvika — Park4Night #23954',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape conservée, à réévaluer par rapport au tracé côtier Helgelandskysten.',services:['À vérifier'],lat:'',lon:''},
    {name:'Park4Night #582192 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/582192',reference:'582192',stopIndex:11,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #698111',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape conservée dans l’ordre du voyage ; détails à compléter.',services:['À vérifier'],lat:'',lon:''},
    {name:'Park4Night #657695 — étape suivante',source:'Park4Night',url:'https://park4night.com/fr/place/657695',reference:'657695',stopIndex:12,status:'selected-pending-details',priority:'next-stage',previousStage:'Park4Night #582192',distanceFromPrevious:'À calculer',driveTimeFromPrevious:'À calculer',notes:'Étape conservée dans l’ordre du voyage ; détails à compléter.',services:['À vérifier'],lat:'',lon:''},

    {name:'Park4Night #697896 — ancien premier arrêt potentiel',source:'Park4Night',url:'https://park4night.com/fr/place/697896',reference:'697896',stopIndex:0,status:'backup',priority:'review',notes:'Ancienne option de secours.',lat:'',lon:''},
    {name:'Park4Night #347908 — ancienne option deuxième nuit',source:'Park4Night',url:'https://park4night.com/fr/place/347908',reference:'347908',stopIndex:1,status:'backup',priority:'review',notes:'Ancienne option de secours.',lat:'',lon:''},
    {name:'Park4Night #565906 — ancienne option troisième nuit',source:'Park4Night',url:'https://park4night.com/fr/place/565906',reference:'565906',stopIndex:2,status:'backup',priority:'review',notes:'Ancienne option de secours.',lat:'',lon:''},
    {name:'Park4Night #153403 — Umeå E4 · plan B légal et pratique',source:'Park4Night',url:'https://park4night.com/fr/place/153403',reference:'153403',stopIndex:3,status:'backup',priority:'umea-practical-backup',notes:'Plan B à Umeå : parking jour/nuit gratuit avec toilettes, poubelles et vidange cassette, mais moins panoramique que #136201.',services:['Gratuit','Toilettes','Poubelles','Vidange cassette'],lat:63.8713,lon:20.4516}
  ];

  if(typeof state==='undefined')return;
  if(!Array.isArray(state.savedCamperStops))state.savedCamperStops=[];
  let changed=false;
  const managed=['664943','359873','188958','136201','293420','696328','121761','84297','38914','697122','84431','81739','23954','610111','698111','582192','657695','347908','565906','153403'];
  candidates.forEach(candidate=>{
    const index=state.savedCamperStops.findIndex(stop=>String(stop.reference||'').includes(candidate.reference)||String(stop.url||'').includes(`/place/${candidate.reference}`));
    if(index<0){state.savedCamperStops.push(candidate);changed=true;}
    else if(managed.includes(candidate.reference)){state.savedCamperStops[index]=Object.assign({},state.savedCamperStops[index],candidate);changed=true;}
  });
  if(changed&&typeof save==='function')save();
})();