'use strict';

(function seedPremiumOvernights(){
  const premium=[
    {name:'25/08 · Alveslohe — halte verte de transit',source:'Park4Night',url:'https://park4night.com/fr/place/664943',reference:'premium-2026-08-25',stopIndex:0,status:'selected',priority:'premium-primary',date:'25/08',notes:'Première nuit volontairement simple après la longue remontée depuis les Yvelines. Arriver assez tôt pour une promenade avec Paddy autour des espaces verts. Vérifier la signalisation de nuit à l’arrivée.',experience:'Halte calme et verte plutôt qu’une aire autoroutière',paddyWalk:'Promenade courte autour des espaces verts et chemins voisins',photoMoment:'Lumière douce du soir dans la campagne du Schleswig-Holstein',services:['Poubelles','Proche A7','Espace pour promener Paddy'],lat:53.7830,lon:9.9179},
    {name:'26/08 · Vätterledens — réveil face au lac Vättern',source:'Park4Night',url:'https://park4night.com/fr/place/359873',reference:'premium-2026-08-26',stopIndex:1,status:'selected',priority:'premium-primary',date:'26/08',notes:'Nuit choisie pour le lac, la baignade et la lumière du soir. Confirmer impérativement l’ouverture après le 15 août avant le voyage.',experience:'Grand lac suédois, horizon ouvert et vraie sensation de Scandinavie',paddyWalk:'Sentiers forestiers et rive du Vättern',photoMoment:'Reflets et brumes éventuelles au lever du jour',services:['Eau','Douches','Toilettes','Électricité','Laverie','Baignade'],lat:57.9250,lon:14.3221},
    {name:'27/08 · Forsgården — petite aire au bord de la rivière',source:'Park4Night',url:'https://park4night.com/fr/place/188958',reference:'premium-2026-08-27',stopIndex:2,status:'selected',priority:'premium-primary',date:'27/08',notes:'Petite adresse volontairement intimiste près de Gävle, au bord de l’eau. Appeler en amont car il n’y a qu’une douzaine d’emplacements.',experience:'Rivière, calme et ambiance de petite ferme plutôt qu’un grand camping',paddyWalk:'Chemin facile le long de la rivière',photoMoment:'Eau calme et végétation à la fin de journée',services:['Eau','Douches','Toilettes','Électricité','Laverie','Cuisine commune'],lat:60.6747,lon:17.0740},
    {name:'28/08 · Umeå — belvédère officiel au-dessus du paysage',source:'Park4Night',url:'https://park4night.com/fr/place/136201',reference:'premium-2026-08-28',stopIndex:3,status:'selected',priority:'premium-primary',date:'28/08',notes:'Aire officielle retenue pour sa plateforme supérieure et sa vue. Plus sauvage qu’un camping classique, avec toilette sèche et foyer.',experience:'Premier vrai bivouac nordique avec horizon dégagé',paddyWalk:'Boucle facile autour du belvédère et des bois',photoMoment:'Ciel du nord, coucher de soleil et éventuelles premières lueurs aurorales',services:['Toilette sèche','Tables','Foyer','Gratuit'],lat:63.8767,lon:20.0187},
    {name:'29/08 · Abisko Mountain Lodge — nuit arctique au pied des montagnes',source:'Site officiel',url:'https://www.abiskomountainlodge.se/',reference:'premium-2026-08-29',stopIndex:4,status:'selected',priority:'premium-primary',date:'29/08',notes:'Nuit confort au cœur du paysage arctique. Réserver et demander une confirmation écrite pour le stationnement du camping-car ainsi que l’accueil de Paddy.',experience:'Montagnes d’Abisko, ciel arctique et vraie pause avant les Lofoten',paddyWalk:'Promenade accessible autour du village et vers les paysages du Torneträsk',photoMoment:'Lumière rasante sur les montagnes et potentiel d’aurore',services:['Lodge','Restaurant','Petit-déjeuner sur réservation'],lat:68.3540,lon:18.8320},
    {name:'30/08 · Hov Camping — plage blanche et océan à Gimsøy',source:'Site officiel',url:'https://hovgard.no/en/camping-caravanning/',reference:'premium-2026-08-30',stopIndex:5,status:'selected',priority:'premium-primary',date:'30/08',notes:'Première nuit aux Lofoten directement sur une plage blanche, avec vue ouverte sur la mer. Réserver à l’avance; le site accepte les camping-cars jusqu’à 5 tonnes et 8,5 m.',experience:'Plage arctique, océan, montagnes et arrivée spectaculaire aux Lofoten',paddyWalk:'Plage de Hov et promenade vers le pied du Hoven',photoMoment:'Coucher de soleil au-dessus de l’océan et silhouettes des chevaux',services:['Douches','Toilettes','Électricité','Vidanges','Laverie','Restaurant','Sauna'],lat:68.3408,lon:14.1166},
    {name:'31/08 · Hov Camping — seconde nuit pour vivre Gimsøy sans courir',source:'Site officiel',url:'https://hovgard.no/en/camping-caravanning/',reference:'premium-2026-08-31',stopIndex:6,status:'selected',priority:'premium-primary',date:'31/08',notes:'Deuxième nuit assumée au même endroit afin de profiter de Henningsvær, des plages de l’est et du retour à Hov pour la meilleure lumière, sans refaire le camp chaque soir.',experience:'Une vraie base côtière premium plutôt qu’une succession de parkings',paddyWalk:'Longue plage de Hov ou promenade calme autour de Gimsøy',photoMoment:'Blue hour sur la plage après le retour d’Henningsvær',services:['Douches','Toilettes','Électricité','Vidanges','Laverie','Restaurant','Sauna'],lat:68.3408,lon:14.1166},
    {name:'01/09 · Uttakleiv — la nuit signature du voyage',source:'Park4Night',url:'https://park4night.com/fr/place/38914',reference:'premium-2026-09-01',stopIndex:7,status:'selected',priority:'premium-signature',date:'01/09',notes:'Notre référence absolue : camping au bord de la plage, sous les montagnes, avec la marche côtière vers Haukland directement depuis le van.',experience:'Dormir face à l’une des plages les plus photogéniques des Lofoten',paddyWalk:'Ancienne route côtière Uttakleiv–Haukland, modulable selon l’énergie',photoMoment:'Galets, vagues longues, montagnes et blue hour depuis le camping',services:['Toilettes','Eau','Vidange cassette','Poubelles'],lat:68.2091,lon:13.5067},
    {name:'02/09 · Lofoten Beach Camp — plage de Skagsanden à Ramberg',source:'Site officiel',url:'https://www.lofotenbeachcamp.no/home-tremont/camping-dr6fg',reference:'premium-2026-09-02',stopIndex:8,status:'selected',priority:'premium-primary',date:'02/09',notes:'Grand camping directement sur la plage, idéalement placé entre Uttakleiv et Reine. Pas de réservation pour les camping-cars : arriver avant 18 h.',experience:'Sable clair, vagues, montagnes et accès facile aux paysages de Flakstad',paddyWalk:'Plage de Skagsanden et sentiers faciles autour de Flakstad',photoMoment:'Reflets sur le sable mouillé et lumière du soir derrière les montagnes',services:['Eau','Électricité','Vidange eaux grises','Vidange cassette','Douches','Toilettes','Cuisine','Bar de plage'],lat:68.0892,lon:13.2364},
    {name:'03/09 · Moskenes Camping — balcon sur le Vestfjord',source:'Site officiel',url:'https://moskenescamping.no/',reference:'premium-2026-09-03',stopIndex:9,status:'selected',priority:'premium-primary',date:'03/09',notes:'Base panoramique pour Hamnøy, Sakrisøy, Reine, Sørvågen et Å. Le camping revendique une vue complète sur le Lofotveggen et le Vestfjord. Réserver en ligne.',experience:'Vue maritime immense, montagnes en muraille et accès immédiat au sud des Lofoten',paddyWalk:'Promenade littorale autour de Moskenes et Sørvågen',photoMoment:'Lever de lumière sur le Vestfjord et silhouettes du Lofotveggen',services:['Électricité','Eau','Douches','Toilettes','Cuisine','Vidanges'],lat:67.9007,lon:13.0457},
    {name:'04/09 · Moskenes Camping — journée météo flexible au meilleur balcon',source:'Site officiel',url:'https://moskenescamping.no/',reference:'premium-2026-09-04',stopIndex:10,status:'selected',priority:'premium-primary',date:'04/09',notes:'Deuxième nuit pour adapter Reine, Å, Hamnøy et les promenades à la météo sans perdre du temps à déplacer le camping-car.',experience:'Rester au cœur du décor lorsque la lumière ou la météo devient exceptionnelle',paddyWalk:'Sørvågen et Å selon le vent et la pluie',photoMoment:'Hamnøy au lever du jour puis lumière du soir depuis le camping',services:['Électricité','Eau','Douches','Toilettes','Cuisine','Vidanges'],lat:67.9007,lon:13.0457},
    {name:'05/09 · Saltstraumen Camping — courant de marée et fjord',source:'Site officiel',url:'https://saltstraumen-camping.no/',reference:'premium-2026-09-05',stopIndex:11,status:'selected',priority:'premium-primary',date:'05/09',notes:'Prendre le ferry Moskenes–Bodø puis rejoindre Saltstraumen. Nuit choisie pour vivre le courant de marée à pied aux meilleures heures plutôt que de remonter par l’E10 et l’E6.',experience:'Un phénomène naturel majeur au bord du fjord et l’entrée idéale vers la route 17',paddyWalk:'Promenade au bord du détroit et vers le pont, en restant loin du courant',photoMoment:'Tourbillons, eau texturée et lumière rasante sous le pont',services:['Eau','Douches','Toilettes','Électricité','Wi-Fi','Laverie','Vidanges'],lat:67.2354,lon:14.6207},
    {name:'06/09 · Storvika — plage sauvage entre mer et montagnes',source:'Park4Night',url:'https://park4night.com/fr/place/23954',reference:'premium-2026-09-06',stopIndex:12,status:'selected',priority:'premium-primary',date:'06/09',notes:'Étape volontairement courte sur l’Helgelandskysten pour profiter des ferries, de la route panoramique et de la longue plage plutôt que de poursuivre jusqu’à Mosjøen.',experience:'Une baie spectaculaire reliée à une plage d’un kilomètre sous les montagnes',paddyWalk:'Longue promenade sur la plage de Storvika',photoMoment:'Pont de pierre, courbes de la baie et lumière de fin de journée',services:['Toilettes ouvertes toute l’année','Aire de service camping-car','Tables','Plage'],lat:66.9602,lon:13.8043},
    {name:'07/09 · Topcamp Havblikk — côte d’Helgeland à Nesna',source:'Site officiel',url:'https://booking.visithelgeland.com/en/hotel/726-topcamp-havblikk',reference:'premium-2026-09-07',stopIndex:13,status:'selected',priority:'premium-primary',date:'07/09',notes:'Camping directement sur le rivage à Nesna, choisi pour prolonger l’Helgelandskysten avec vues maritimes et services complets.',experience:'Rivage paisible, îles et montagnes de la côte d’Helgeland',paddyWalk:'Promenade du littoral et courte montée vers les points de vue de Nesna',photoMoment:'Îles superposées dans la brume et coucher de soleil sur la mer',services:['Douches','Toilettes','Laverie','Restaurant saisonnier','Aire camping-car'],lat:66.1990,lon:13.0180},
    {name:'08/09 · Flakk Camping — fjord de Trondheim',source:'Site officiel',url:'https://flakk-camping.no/',reference:'premium-2026-09-08',stopIndex:14,status:'selected',priority:'premium-primary',date:'08/09',notes:'Nuit au bord du Trondheimsfjord, suffisamment proche de Trondheim tout en gardant une vraie sensation de nature et d’espace.',experience:'Fjord ouvert et lumière maritime plutôt qu’un camping urbain',paddyWalk:'Promenade tranquille le long du rivage',photoMoment:'Ferry, fjord et lumière du soir vers Fosen',services:['Camping','Sanitaires','Électricité','Accès au fjord'],lat:63.4510,lon:10.2010},
    {name:'09/09 · Sjoa Camping — rivière et vallée de Gudbrandsdalen',source:'Site officiel',url:'https://sjoacamping.no/',reference:'premium-2026-09-09',stopIndex:15,status:'selected',priority:'premium-primary',date:'09/09',notes:'Étape de retour choisie pour la rivière Sjoa et les montagnes de la vallée, plus mémorable qu’un arrêt autoroutier autour de Lillehammer.',experience:'Rivière vive, forêt et ambiance de vallée norvégienne',paddyWalk:'Chemins faciles près de la rivière en restant à distance des rapides',photoMoment:'Eaux turquoise, rochers et brume matinale',services:['Camping','Douches','Toilettes','Électricité'],lat:61.6740,lon:9.5360},
    {name:'10/09 · Ställplats Lerum — dernière soirée scandinave au lac Aspen',source:'Park4Night',url:'https://park4night.com/fr/place/582192',reference:'premium-2026-09-10',stopIndex:16,status:'selected',priority:'premium-primary',date:'10/09',notes:'Dernière nuit scandinave au bord du lac, avec tous les services nécessaires avant la longue descente finale. Réservation en ligne obligatoire.',experience:'Un dernier lac suédois et un coucher de soleil au bord de l’eau',paddyWalk:'Promenade sur les rives du lac Aspen',photoMoment:'Reflets du soir et brume possible au petit matin',services:['Eau','Douches','Toilettes','Électricité','Wi-Fi','Laverie','Vidanges','Baignade'],lat:57.7580,lon:12.2528}
  ];

  if(typeof state==='undefined')return;
  if(!Array.isArray(state.savedCamperStops))state.savedCamperStops=[];
  const legacyRefs=['664943','359873','188958','136201','293420','696328','121761','84297','38914','697122','84431','81739','23954','610111','698111','582192','657695','697896','347908','565906','153403'];
  state.savedCamperStops=state.savedCamperStops.filter(stop=>{
    const ref=String(stop.reference||'');
    const url=String(stop.url||'');
    return !legacyRefs.some(id=>ref.includes(id)||url.includes('/place/'+id))&&!ref.startsWith('premium-2026-');
  });
  state.savedCamperStops.push(...premium);
  if(typeof save==='function')save();
})();