'use strict';
(function(){
const DAYS=[
{d:9,date:'2 septembre 2026',route:'Moskenes → Djupfjorden → Reinebringen → Reine → Flakstad → Moskenes',title:'Reinebringen — la journée parfaite',story:[`Il y a des journées qui se racontent, et puis il y a celles qu’on voudrait juste garder intactes quelque part. Cette journée aux Lofoten en fait partie.`,`Premier petit exploit de la journée : Sorya s’est levée tôt. Et elle ne l’a pas regretté. Vers 7 h 30, nous arrivons au parking de Steffenakken, juste à côté du pont de Djupfjorden. Nous traversons le pont à pied puis suivons l’accès jusqu’au départ de Reinebringen. L’air est frais, la foule n’est pas encore là et les conditions sont parfaites.`,`Très vite, notre expédition prend des airs officiels : Sorya devient le Sherpa, Paddy le Super VIP, porté avec tous les honneurs, et Olivier, modestement, le guide. Pour Olivier, entraîné à la randonnée, la montée ne présente pas de difficulté particulière. Pour Sorya, qui n’est pas entraînée à ce genre d’effort, c’est un véritable exploit : près de deux mille marches avalées à son rythme, sans rien lâcher. Les joues rougissent, les jambes protestent sans doute, mais le sourire est encore là au sommet.`,`Et puis le monde s’ouvre sous nos pieds : Reine, les fjords découpés, les montagnes surgissant de la mer, les villages minuscules et cette lumière limpide qui donne au paysage quelque chose d’irréel. Une de ces vues pour lesquelles les mots paraissent toujours insuffisants.`,`Nous redescendons tranquillement et nous arrêtons à Reine pour un café bien mérité. Puis nous reprenons la route vers Flakstad, où nous terminons la journée par une balade beaucoup plus douce d’environ une heure à une heure vingt, toujours sous cette lumière exceptionnelle. Vers 17 h, retour à Moskenes Camping. Température parfaite, ciel pur, soleil, Reinebringen, Sorya au sommet : tout s’est aligné. Certaines journées sont simplement rares. Celle-ci restera comme l’une des plus belles du voyage.`]},
{d:8,date:'1er septembre 2026',route:'Ramberg → Vikten → Å → Yttersand → Moskenes',title:'Enfin, ralentir',story:[`Vikten, Ramberg, Å puis une balade côtière à Yttersand avant de rejoindre Moskenes Camping. Après la longue remontée depuis la France, le voyage ralentit enfin.`]},
{d:7,date:'31 août 2026',route:'Sandsletta → Haukland → Uttakleiv → Ramberg',title:'Haukland, Uttakleiv et les élans',story:[`Rencontre extraordinaire avec les élans sauvages, Haukland Beach, boucle vers Uttakleiv et fin de journée lumineuse à Ramberg.`]},
{d:6,date:'30 août 2026',route:'Nord de la Suède → Narvik → Sandsletta',title:'L’entrée dans les Lofoten',story:[`Une très longue route sous la pluie avant l’apparition des montagnes plongeant dans la mer : l’arrivée rêvée dans les Lofoten.`]},
{d:5,date:'29 août 2026',route:'Umeå → nord de la Suède',title:'Le diagnostic EGR',story:[`Après plusieurs garages à Umeå, le diagnostic tombe : vanne EGR. Le garage confirme que le voyage peut continuer.`]},
{d:4,date:'28 août 2026',route:'Skuleskogen → Umeå',title:'Skuleskogen et le voyant moteur',story:[`Une balade prévue courte devient quatre heures dans Skuleskogen. À Umeå, le voyant moteur s’allume.`]},
{d:3,date:'27 août 2026',route:'Suède · cap au nord',title:'Toujours plus au nord',story:[`Longue remontée de la Suède, quelques haltes et une nuit calme face à un lac.`]},
{d:2,date:'26 août 2026',route:'Bispingen → Danemark → Suède',title:'Danemark et Suède',story:[`Les grands ponts scandinaves marquent l’entrée véritable dans le Nord.`]},
{d:1,date:'25 août 2026',route:'Chevreuse → Bispingen',title:'La route vers le nord commence',story:[`Départ vers 4 h 30. Près de 900 kilomètres plus tard, Bispingen offre une première nuit calme et bucolique.`]}
];
const tabs=[['home','Essentiel'],['route','Itinéraire'],['story','Récits'],['bookings','Réservations'],['van','Camping-car'],['budget','Budget']];
function nav(a){document.getElementById('nav').innerHTML=tabs.map(x=>`<button data-tab="${x[0]}" class="${x[0]===a?'active':''}">${x[1]}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>render(b.dataset.tab));}
function home(){return `<div class="stack"><section class="card hero-card"><p class="eyebrow">2 SEPTEMBRE 2026</p><h2>Reinebringen : une journée rare</h2><p class="lead">Départ à la fraîche, près de deux mille marches, Sorya au sommet, ciel limpide et fjords de Reine sous les pieds. Retour à Moskenes après une balade à Flakstad.</p></section><section class="card"><h2>Roadbook essentiel à jour</h2><p>Le réel et le journal sont maintenant consolidés jusqu’à aujourd’hui.</p></section></div>`}
function route(){return `<div class="stack"><section class="card"><p class="eyebrow">ITINÉRAIRE RÉEL</p><h2>Du départ à aujourd’hui</h2>${[...DAYS].reverse().map(x=>`<article class="timeline-item"><div class="day-badge">J${x.d}</div><div><h3>${x.date}</h3><p>${x.route}</p></div></article>`).join('')}</section></div>`}
function story(){return `<div class="stack"><section class="card"><p class="eyebrow">JOURNAL</p><h2>Les récits du voyage</h2></section>${DAYS.map(x=>`<article class="card story-card"><p class="eyebrow">JOUR ${x.d} · ${x.date}</p><h2>${x.title}</h2>${x.story.map(p=>`<p>${p}</p>`).join('')}</article>`).join('')}</div>`}
function bookings(){return `<div class="stack"><section class="card"><h2>Réservations</h2><p><b>Moskenes Camping</b> jusqu’au 4 septembre à midi.</p><p><b>Saga Adventures</b> : kayak vendredi 4 septembre, 10 h–13 h.</p></section></div>`}
function van(){return `<div class="stack"><section class="card"><h2>Camping-car</h2><p>Diagnostic EGR effectué à Umeå. Poursuite du voyage autorisée avec surveillance du véhicule.</p></section></div>`}
function budget(){return `<div class="stack"><section class="card"><h2>Budget réel</h2><p>Uniquement les dépenses réellement enregistrées ; aucune estimation ajoutée.</p></section></div>`}
function render(a='home'){nav(a);let f={home,route,story,bookings,van,budget}[a];document.getElementById('app').innerHTML=f();window.scrollTo(0,0)}
document.addEventListener('DOMContentLoaded',()=>render());
})();
