'use strict';

(function roadbookEssential(){
  const TABS=[['home','Essentiel'],['route','Itinéraire'],['story','Récits'],['bookings','Réservations'],['van','Camping-car'],['budget','Budget']];
  const TODAY='1er septembre 2026';
  const GMAIL=query=>`https://mail.google.com/mail/u/0/#search/${encodeURIComponent(query)}`;
  const MAP=query=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const ACTUAL=[
    {day:1,date:'25 août',from:'Chevreuse',to:'Bispingen',via:'Belgique · Allemagne',night:'Bispingen · aire nature',what:'Environ 900 km et première nuit bucolique après la grande route.'},
    {day:2,date:'26 août',from:'Bispingen',to:'Sud de la Suède',via:'Danemark · Storebælt · Øresund',night:'Bord d’un lac',what:'Traversée des grands ponts et entrée en Scandinavie.'},
    {day:3,date:'27 août',from:'Sud de la Suède',to:'Suède centrale',via:'Région de Stockholm · Sveriges Bilmuseum',night:'Camping calme',what:'Longue remontée vers le nord, avec quelques pauses choisies.'},
    {day:4,date:'28 août',from:'Suède centrale',to:'Umeå',via:'Skuleskogen National Park',night:'Umeå',what:'Quatre heures dans la forêt, puis apparition du voyant moteur.'},
    {day:5,date:'29 août',from:'Umeå',to:'Nord de la Suède',via:'Garages · Autostar · plage isolée',night:'Étape vers le nord',what:'Diagnostic EGR et confirmation professionnelle que le voyage peut continuer.'},
    {day:6,date:'30 août',from:'Nord de la Suède',to:'Sandsletta Camping',via:'Narvik · E10',night:'Sandsletta Camping',what:'Très longue journée sous la pluie et arrivée spectaculaire dans les Lofoten.'},
    {day:7,date:'31 août',from:'Sandsletta',to:'Ramberg Resort',via:'Haukland · Uttakleiv',night:'Ramberg Resort',what:'Élans sauvages, boucle d’environ 8 km et lumière du soir sur Ramberg Beach.'},
    {day:8,date:'1er septembre',from:'Ramberg Resort',to:'Moskenes Camping',via:'Vikten · Ramberg · Å · Yttersand',night:'Moskenes · camp de base',what:'Villages, petite balade côtière et décision de ralentir pendant trois jours.'}
  ];

  const STORIES=[
    {day:1,date:'25 August 2026',title:'The road north begins',text:[`A very early start from the Paris region, at around 4:30 a.m. The first day was all about putting distance behind us and beginning the long journey north. Nearly 900 kilometres through France, Belgium and Germany, with that special feeling that comes when an adventure finally becomes real after weeks of preparation. By early evening we reached Bispingen and our first overnight stop, a peaceful motorhome area surrounded by nature. After a day dominated by motorways, the contrast was immediate: quiet, green and almost bucolic. The perfect first night on the road.`]},
    {day:2,date:'26 August 2026',title:'Across Denmark and into Sweden',text:[`Back on the road for another major travelling day. Germany gave way to Denmark, then came the two great Scandinavian crossings: Storebælt and Øresund. Bridges, sea and huge horizons made the drive itself part of the journey. Crossing into Sweden felt like another milestone: we were properly heading into Scandinavia now. The day ended beside a lake, in an atmosphere completely different from the motorway hours that had come before it — calm water, silence and the first real sense of the northern landscapes we had come to find.`]},
    {day:3,date:'27 August 2026',title:'Sweden, further and further north',text:[`Another long stage north through Sweden, passing the Stockholm region and steadily watching the landscape change. We stopped along the way, including a visit around Sveriges Bilmuseum and a grocery break, before continuing towards our evening campsite. It was a demanding driving day, but the rhythm of the road was settling in: kilometres, short discoveries, walks and quiet places to sleep. The campsite that evening was particularly pleasant and gave us exactly the peaceful pause we needed before continuing north.`]},
    {day:4,date:'28 August 2026',title:'Skuleskogen — and the warning light',text:[`The morning began in dense fog, the kind that makes the world beyond the windscreen almost disappear. After groceries, we broke up the drive with what was meant to be a modest walk in Skuleskogen National Park. It became a wonderful four-hour immersion in the forest and lakes, a real escape from the road and one of those unexpected stops that end up defining a journey. We continued to Umeå in the evening — and then the mood changed. A warning light appeared on the campervan. Calls, assistance and uncertainty replaced the tranquillity of the hike. We went to bed without a clear diagnosis, knowing that the next morning would begin with garages rather than kilometres.`]},
    {day:5,date:'29 August 2026',title:'The EGR diagnosis — and the decision to continue',text:[`The day started with a tour of garages in Umeå. The first place did not inspire enough confidence; the second could not properly diagnose the vehicle. Finally, at Autostar, we got an answer: a malfunction linked to the EGR valve. Most importantly, the workshop told us that we could continue the journey, with clear instructions on what to do if the van lost power. The relief was enormous. After the stress of the previous evening and the morning’s uncertainty, we stopped at a hidden beach and simply enjoyed being able to carry on. Then we pointed the van north again. The Lofoten adventure was still alive.`]},
    {day:6,date:'30 August 2026',title:'Into the Lofoten',text:[`A very long day on the road, much of it under rain. We kept moving north and west until the scenery began to transform around us. Near Narvik and on the approach to the islands, the landscape suddenly became monumental: mountains rising straight from the water, dark skies, waterfalls and roads threading through scenery that hardly seemed real. After so many kilometres across Europe and Sweden, this was the moment we had been waiting for — our arrival in the Lofoten. We ended the day at Sandsletta Camping, tired after the drive but overwhelmed by the feeling of finally being here. The journey north had become the journey through the islands.`]},
    {day:7,date:'31 August 2026',title:'Haukland, Uttakleiv and the moose of the Lofoten',text:[`Another morning departure, with the usual ritual of getting everything ready for the day’s hike. On the narrow road towards Haukland Beach, the day immediately became extraordinary: just across the road, a female moose and a young one appeared in the wild. We stopped, watched and took a few photos and videos, amazed to see them so close and completely free. It was our first encounter with wild moose and an unforgettable welcome to this part of the Lofoten.`,`At Haukland, the sky was still grey but the rain held off. The beach and sea were so beautiful that the weather hardly mattered. We spent some time on the sand, then warmed up at Haukland Beach Café with banana bread and a latte. Then came the Haukland–Uttakleiv loop, around eight kilometres. The trail was extremely muddy and the first climbing came quickly, but once across, everything opened into an easy, magnificent walk.`,`As we left Haukland, another extraordinary wildlife encounter: the female, the young ones, and this time an adult male with magnificent antlers. We finally chose Ramberg Resort and ended the day walking along Ramberg Beach. White sand, almost nobody around and a shy sun occasionally finding its way through the clouds — a truly incredible day.`]},
    {day:8,date:'1 September 2026',title:'At last, learning to slow down',text:[`Another early start. With Paddy travelling with us, sleeping late has quietly disappeared from the programme; every morning, he makes sure that the day begins promptly.`,`Our first stop was Vikten, hoping to find breakfast at the little café beside the glassblower’s workshop. The setting was still as beautiful as ever, tucked between mountains and ocean, but the season was already coming to an end. There were no pastries left and none of the special hot drinks we had imagined. So we moved on.`,`In Ramberg, we filled the van and spotted a café I remembered for its delicious breakfasts. It seemed like the perfect second chance — until we discovered that dogs were not allowed inside. We continued south, all the way to Å. There, the traditional bakery promised old fishermen’s buildings, the smell of bread and the atmosphere of the edge of the world. Yet our third attempt brought a third small disappointment. The pastries were pleasant but unremarkable — but they finally filled our stomachs.`,`We took our time exploring Å, then drove towards Yttersand for a short coastal walk. There was no challenge to complete and no distance to chase: only the ocean, an immense beach and mountains dropping straight into the water. Simply walking and looking around felt restorative.`,`We eventually reached Moskenes Camping. It was an immediate and wonderful surprise: a superb setting, a magnificent view and the calm atmosphere we now needed. Since leaving France, the journey had been a succession of roads, hikes, discoveries and campsite changes. Before beginning the long journey home, that rhythm needed to be broken. For three days, Moskenes would be our home — and, at last, the journey could slow down.`]}
  ];

  const EURO_EXPENSES=[
    ['2026-08-21','Courses','Avant départ',77.00,'Stock complémentaire'],
    ['2026-08-25','Péage','France',23.90,'Péage réellement payé'],
    ['2026-08-25','Carburant','Allemagne',136.00,'Montant communiqué · 44 L mentionnés'],
    ['2026-08-25','Nuit','Bispingen',30.00,'Aire / nuit'],
    ['2026-08-26','Route','À préciser',100.00,'Montant communiqué, catégorie exacte à confirmer'],
    ['2026-08-26','Nuit','Suède',25.00,'Camping'],
    ['2026-08-29','Carburant','Suède',107.00,'Montant en euros communiqué'],
    ['2026-08-29','Nuit','Suède',45.61,'Camping'],
    ['2026-08-30','Carburant','Suède',57.52,'Montant corrigé'],
    ['2026-08-31','Parking','Hauklandstranda',16.28,'Parking randonnée'],
    ['2026-08-31','Café / achat','Haukland Beach Café',55.38,'Café, banana bread et livre'],
    ['2026-08-31','Nuit','Ramberg Resort',54.92,'Camping'],
    ['2026-09-01','Nuit','Moskenes Camping',53.83,'Réservation du 1er au 2 septembre · payée'],
    ['2026-09-01','Boulangerie','Å',12.48,'Petit-déjeuner'],
    ['2026-09-01','Kayak','Saga Adventures',119.59,'1 245,50 NOK débités en euros · payé']
  ];
  const FOREIGN=[
    ['2026-08-26','Pont Øresund','1 040,00 DKK','Conversion bancaire exacte à ajouter'],
    ['2026-08-26','Pont Storebælt','645,00 DKK','Conversion bancaire exacte à ajouter'],
    ['2026-08-26','Carburant Suède','1 173,25 SEK','Conversion bancaire exacte à ajouter'],
    ['2026-08-29','Courses Suède','1 189,00 SEK','Conversion bancaire exacte à ajouter'],
    ['2026-08-30','Courses Suède','1 194,40 SEK','Conversion bancaire exacte à ajouter'],
    ['2026-08-30','Carburant Norvège','844,07 NOK','Conversion bancaire exacte à ajouter'],
    ['2026-08-30','Sandsletta Camping','450,00 NOK','Conversion bancaire exacte à ajouter'],
    ['2026-08-30','Douches','40,00 NOK','Conversion bancaire exacte à ajouter'],
    ['2026-09-01','Moskenes Camping · extension','1 109,00 NOK','Payé · conversion bancaire exacte à ajouter']
  ];
  const ROAD_SURFER=2285;

  function fmt(value){return Number(value).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';}
  function nav(active){const target=document.getElementById('nav');target.innerHTML=TABS.map(([id,label])=>`<button data-tab="${id}" class="${id===active?'active':''}">${label}</button>`).join('');target.querySelectorAll('button').forEach(button=>button.onclick=()=>render(button.dataset.tab));}
  function render(active='home'){nav(active);const views={home:homeView,route:routeView,story:storyView,bookings:bookingsView,van:vanView,budget:budgetView};document.getElementById('app').innerHTML=views[active]();window.scrollTo(0,0);}

  function homeView(){return `<div class="stack">
    <section class="card hero-card"><p class="eyebrow">AUJOURD’HUI · ${TODAY.toUpperCase()}</p><h2>Moskenes devient le camp de base</h2><p class="lead">Après huit jours de route et de découvertes, le rythme ralentit enfin. Le camping est confirmé jusqu’au vendredi 4 septembre à midi, avec une sortie kayak réservée vendredi matin.</p><div class="route-flow"><span>Ramberg</span><i>→</i><span>Vikten</span><i>→</i><span>Å</span><i>→</i><span>Yttersand</span><i>→</i><b>Moskenes</b></div></section>
    <section class="status-grid"><div class="good"><span class="tag confirmed">CONFIRMÉ</span><h3>Moskenes Camping</h3><p>Du 1er septembre 12 h au 4 septembre 12 h, en deux réservations successives.</p></div><div class="good"><span class="tag confirmed">CONFIRMÉ</span><h3>Kayak Reine Fjord</h3><p>Vendredi 4 septembre, 10 h–13 h. Arrivée demandée à 9 h 50 à Hamnøya.</p></div><div class="notice"><span class="tag">À RECALER</span><h3>Grand retour</h3><p>L’ancien départ du 3 septembre est remplacé par les réservations confirmées jusqu’au 4.</p></div><div class="danger-note"><span class="tag">SURVEILLANCE</span><h3>Voyant moteur / EGR</h3><p>Le garage et Roadsurfer autorisent la poursuite. Appeler si nouveau voyant, perte de puissance ou comportement inhabituel.</p></div></section>
    <section class="card notice"><h2>Vendredi 4 septembre : point logistique</h2><p>Le kayak commence à 10 h alors que le check-out du camping est à midi. Il faut donc libérer l’emplacement et partir avec le camping-car avant la sortie, puis être au rendez-vous à <b>9 h 50</b>. Depuis Moskenes, vous êtes déjà du bon côté du tunnel de Nappstraumen.</p></section>
    <section class="card"><p class="eyebrow">CE QUI RESTE DANS LE ROADBOOK</p><h2 class="section-title">Six vues, rien de superflu</h2><div class="metric-grid"><div class="mini-card"><h3>Itinéraire</h3><p>Le réel jusqu’au Jour 8 et les prochaines échéances confirmées.</p></div><div class="mini-card"><h3>Récits</h3><p>Les huit journées, dans une narration homogène.</p></div><div class="mini-card"><h3>Réservations</h3><p>Camping, kayak et location, vérifiés dans Gmail.</p></div><div class="mini-card"><h3>Budget</h3><p>Montants exacts en euros et devises encore à convertir séparément.</p></div></div></section>
  </div>`;}

  function routeView(){return `<div class="stack">
    <section class="card"><p class="eyebrow">VOYAGE RÉEL · JOURS 1 À 8</p><h2>Ce qui s’est réellement passé</h2><div class="timeline">${ACTUAL.map(d=>`<article><time>J${d.day}<br>${esc(d.date)}</time><div><h3>${esc(d.from)} → ${esc(d.to)}</h3><p><b>Passages :</b> ${esc(d.via)}</p><p>${esc(d.what)}</p><p class="muted"><b>Nuit :</b> ${esc(d.night)}</p></div></article>`).join('')}</div></section>
    <section class="card good"><p class="eyebrow">PROCHAINES ÉCHÉANCES CONFIRMÉES</p><h2>La réalité qui pilote la suite</h2><div class="timeline"><article><time>2–4 sept.</time><div><h3>Moskenes Camping</h3><p>Deux nuits supplémentaires, emplacement 25 secteur B. Check-out vendredi à midi.</p></div></article><article><time>4 sept.<br>9 h 50</time><div><h3>Rendez-vous kayak à Hamnøya</h3><p>Sortie Reine Fjord de 10 h à 13 h. Camping-car déjà libéré du camping.</p></div></article><article><time>12 sept.<br>16 h</time><div><h3>Restitution Roadsurfer</h3><p>33 route de Versailles, Champlan. Plein, vidanges, nettoyage et photos avant restitution.</p></div></article></div></section>
    <section class="card notice"><p class="eyebrow">GRAND RETOUR · VERSION À RECALER</p><h2>Les destinations restent, les anciennes dates ne sont plus valides</h2><p>L’email de planification prévoyait un départ des Lofoten le 3 septembre. Les réservations Gmail confirment désormais Moskenes et le kayak jusqu’au 4 septembre : ce calendrier est donc obsolète. Le fil conducteur souhaité reste :</p><p class="route-flow"><span>Narvik</span><i>→</i><span>Saltstraumen</span><i>→</i><span>Saltfjellet / cercle polaire</span><i>→</i><span>Marmorslottet</span><i>→</i><span>Trondheim</span><i>→</i><span>Atlantic Ocean Road</span><i>→</i><span>Geiranger</span><i>→</i><span>Göteborg</span><i>→</i><span>Lübeck</span><i>→</i><span>Maison</span></p><p class="muted">Règle maintenue : zéro ferry. Un nouveau calendrier réaliste doit être construit à partir du départ effectif après le kayak.</p></section>
  </div>`;}

  function storyView(){return `<div class="stack"><section class="card"><p class="eyebrow">TRAVEL JOURNAL · DAYS 1–8</p><h2>Our road to the Lofoten</h2><p>A living account of the journey as it actually happened. Open a day to read it.</p></section>${STORIES.slice().reverse().map(s=>`<details class="card story" ${s.day===8?'open':''}><summary><p class="eyebrow">DAY ${s.day} · ${esc(s.date)}</p><h2>${esc(s.title)}</h2></summary>${s.text.map(p=>`<p>${esc(p)}</p>`).join('')}</details>`).join('')}</div>`;}
  function gmailButton(query,label='Retrouver dans Gmail'){return `<a class="btn" href="${GMAIL(query)}" target="_blank" rel="noopener">${esc(label)} ↗</a>`;}

  function bookingsView(){return `<div class="stack">
    <section class="card"><p class="eyebrow">RÉSERVATIONS VÉRIFIÉES DANS GMAIL</p><h2>Tout ce qui est confirmé, au même endroit</h2><p>Les codes d’accès, mots de passe et liens privés ne sont volontairement pas affichés sur cette page publique. Les boutons Gmail permettent de les retrouver dans votre compte.</p></section>
    <section class="card reservation-card"><span class="tag confirmed">PAYÉ · CONFIRMÉ</span><h2>Moskenes Camping · 1er → 2 septembre</h2><div class="facts"><div class="fact"><small>Emplacement</small><b>59 · secteur E</b></div><div class="fact"><small>Horaires</small><b>12 h → 12 h</b></div><div class="fact"><small>Voyageurs</small><b>2 personnes</b></div><div class="fact"><small>Montant</small><b>561,80 NOK · 53,83 € débité</b></div></div><p><b>Adresse :</b> Moskenesvågen, 8392 Sørvågen · <b>Contact :</b> +47 99 48 94 05 · booking@moskenescamping.no</p><div class="action-row">${gmailButton('subject:"Additional information about your booking at Moskenes Camping" 5403a9','Code d’accès dans Gmail')}${gmailButton('subject:"Your booking with Moskenes Camping" 5403a9','Confirmation Gmail')}</div></section>
    <section class="card reservation-card"><span class="tag confirmed">PAYÉ · CONFIRMÉ</span><h2>Moskenes Camping · 2 → 4 septembre</h2><div class="facts"><div class="fact"><small>Emplacement</small><b>25 · secteur B</b></div><div class="fact"><small>Horaires</small><b>12 h → 12 h</b></div><div class="fact"><small>Voyageurs</small><b>2 personnes</b></div><div class="fact"><small>Montant</small><b>1 109,00 NOK</b></div></div><p><b>Pratique :</b> câble électrique d’au moins 20 m. Cuisine fermée 12 h–13 h, douches fermées 12 h–14 h et bâtiment sanitaire 1 fermé la nuit de minuit à 5 h. Le bâtiment sanitaire 2 n’est plus ouvert après le 31 août.</p><p class="muted">Annulation indiquée : remboursement 100 % jusqu’à 7 jours avant, 50 % jusqu’à 3 jours avant — délais déjà dépassés au moment de cette mise à jour.</p><div class="action-row">${gmailButton('subject:"Additional information about your booking at Moskenes Camping" c4ed22','Code d’accès dans Gmail')}${gmailButton('subject:"Your booking with Moskenes Camping" c4ed22','Confirmation Gmail')}</div></section>
    <section class="card reservation-card good"><span class="tag confirmed">PAYÉ · CONFIRMÉ</span><h2>Saga Adventures · Explore Reine Fjord by kayak</h2><div class="facts"><div class="fact"><small>Date et heure</small><b>Vendredi 4 sept. · 10 h–13 h</b></div><div class="fact"><small>Rendez-vous</small><b>9 h 50</b></div><div class="fact"><small>Participant</small><b>1 personne</b></div><div class="fact"><small>Montant</small><b>1 245,50 NOK · 119,59 € débité</b></div></div><p><b>Lieu :</b> Hamnøya 29, Reine, Lofoten 8390 · arrêt de bus Toppøya. Parking gratuit prévu, y compris pour grands vans et camping-cars.</p><p><b>À porter :</b> vêtements outdoor adaptés, veste de pluie, chaussures légères ou baskets. Éviter les grosses chaussures de randonnée, qui gênent le contrôle du gouvernail. Aucun niveau préalable en kayak n’est requis.</p><p><b>Fourni :</b> équipement spécifique, gilet, pagaie et combinaison étanche selon l’activité. Utiliser les toilettes avant le départ et arriver à l’heure : les retardataires peuvent manquer la sortie.</p><p><b>Annulation :</b> remboursement ou crédit complet jusqu’à 48 h avant ; remboursement complet si Saga annule pour météo ou sécurité. Contact : +47 414 13 079 · aguaviva.roman@gmail.com.</p><div class="action-row"><a class="btn primary" href="${MAP('Hamnøya 29 Reine Lofoten 8390')}" target="_blank" rel="noopener">Ouvrir le rendez-vous ↗</a>${gmailButton('subject:"Confirmation: Explore Reine Fjord by kayak"','Confirmation Gmail')}</div></section>
    <section class="card reservation-card"><span class="tag confirmed">LOCATION EN COURS</span><h2>Roadsurfer · Cozy Cottage</h2><div class="facts"><div class="fact"><small>Période</small><b>24 août 16 h → 12 sept. 16 h</b></div><div class="fact"><small>Agence</small><b>Champlan</b></div><div class="fact"><small>Montant contractuel</small><b>2 285,00 €</b></div><div class="fact"><small>Paiement indiqué</small><b>2 195,00 € payé · 90,00 € restant</b></div></div><p><b>Inclus :</b> kilométrage illimité, porte-vélos 2 vélos, 2 conducteurs, couverture Basic avec franchise de 3 000 €. Caution : 800 € par carte de crédit, American Express non acceptée.</p><p><b>Adresse :</b> 33 route de Versailles, 91160 Champlan. <b>Assistance immobilisante :</b> +49 89 21094351.</p><div class="action-row">${gmailButton('subject:"Ton contrat de location" 3641456462','Contrat Gmail')}${gmailButton('subject:"Yellow warning light" 3641456462','Dossier EGR Gmail')}</div></section>
  </div>`;}

  function vanView(){return `<div class="stack">
    <section class="card hero-card"><p class="eyebrow">CAMPING-CAR · SITUATION ACTUELLE</p><h2>Base Moskenes · plein effectué à Ramberg</h2><p>Aucun pourcentage d’eau, d’eaux grises ou de batterie n’est affiché tant qu’une mesure réelle n’a pas été transmise.</p></section>
    <section class="card danger-note"><p class="eyebrow">VOYANT MOTEUR · DIAGNOSTIC CONFIRMÉ</p><h2>Vanne EGR · code P045F00</h2><p>Le garage a constaté une vanne EGR bloquée en position fermée et l’a traitée. Le garage puis Roadsurfer ont confirmé par écrit que le voyage pouvait continuer dans les conditions actuelles.</p><p><b>Contacter immédiatement Roadsurfer si :</b> le voyant change ou revient, un nouveau voyant apparaît, le véhicule perd de la puissance ou présente un comportement inhabituel.</p><p><b>Si perte de puissance :</b> s’arrêter en sécurité, couper le moteur, attendre puis redémarrer, conformément au conseil reçu — et contacter Roadsurfer.</p></section>
    <section class="card"><h2>Réparation et justificatifs</h2><p>Une réparation doit être précédée d’un devis approuvé par l’équipe Damage de Roadsurfer. Le coût est d’abord avancé, puis remboursé si les conditions de couverture sont remplies. Conserver tous les diagnostics, devis, factures et tickets de carburant.</p><p>Si l’aller-retour jusqu’à un atelier dépasse 120 km, Roadsurfer indique pouvoir couvrir le carburant supplémentaire au-delà de 120 km sur présentation des reçus.</p></section>
    <section class="card"><h2>Restitution · 12 septembre avant 16 h</h2><div class="status-grid"><div><h3>Carburant</h3><p>Faire le plein et vérifier l’AdBlue si nécessaire.</p></div><div><h3>Fluides</h3><p>Vidanger eaux grises et toilettes ; niveau d’eau conforme.</p></div><div><h3>État</h3><p>Nettoyage, photos intérieures/extérieures et inventaire.</p></div><div><h3>Documents</h3><p>Conserver le dossier EGR et toutes les factures.</p></div></div></section>
  </div>`;}

  function budgetView(){const operational=EURO_EXPENSES.reduce((sum,row)=>sum+row[3],0);const total=ROAD_SURFER+operational;return `<div class="stack">
    <section class="card hero-card"><p class="eyebrow">BUDGET RÉEL · AU ${TODAY.toUpperCase()}</p><div class="budget-total">${fmt(total)}</div><p class="budget-sub">Coût contractuel Roadsurfer inclus (${fmt(ROAD_SURFER)}) + ${fmt(operational)} de dépenses confirmées en euros.</p><p class="muted">À ajouter après conversion bancaire exacte : 1 685 DKK + 3 556,65 SEK + 2 443,07 NOK. Aucun taux de change estimé n’est utilisé.</p></section>
    <section class="card notice"><h2>Point de vigilance</h2><p>La confirmation Roadsurfer du 13 août indique un total de <b>2 285 €</b>, dont <b>2 195 € déjà payés</b> et <b>90 € restant à payer</b> à cette date. Le budget compte le coût contractuel complet une seule fois.</p></section>
    <section class="card"><p class="eyebrow">DÉPENSES EN EUROS</p><h2>Montants confirmés et totalisés</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Catégorie</th><th>Lieu</th><th>Montant</th><th>Détail</th></tr></thead><tbody><tr><td>24/08</td><td>Location</td><td>Roadsurfer</td><td class="money"><b>${fmt(ROAD_SURFER)}</b></td><td>Coût contractuel complet</td></tr>${EURO_EXPENSES.map(r=>`<tr><td>${r[0].split('-').reverse().slice(0,2).join('/')}</td><td>${esc(r[1])}</td><td>${esc(r[2])}</td><td class="money"><b>${fmt(r[3])}</b></td><td>${esc(r[4])}</td></tr>`).join('')}</tbody></table></div></section>
    <section class="card"><p class="eyebrow">DEVISES D’ORIGINE</p><h2>Payé, mais conversion bancaire exacte manquante</h2><p class="source-note">Ces dépenses ne sont pas encore ajoutées au total en euros afin d’éviter un taux inventé ou un double comptage.</p><div class="table-wrap"><table><thead><tr><th>Date</th><th>Dépense</th><th>Montant d’origine</th><th>Statut</th></tr></thead><tbody>${FOREIGN.map(r=>`<tr><td>${r[0].split('-').reverse().slice(0,2).join('/')}</td><td>${esc(r[1])}</td><td class="money pending"><b>${esc(r[2])}</b></td><td>${esc(r[3])}</td></tr>`).join('')}</tbody></table></div></section>
  </div>`;}

  document.addEventListener('DOMContentLoaded',()=>{render('home');if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});});
})();
